import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import{batchNodeExpectedState,createBatchNodeRequestTracker,decodeBatchNodeResult,MAX_BATCH_NODES}from'../batch-node-admin';
const SQL=readFileSync('supabase/migrations/20260915170000_admin_batch_node_mutation.sql','utf8');const UI=readFileSync('src/components/admin/BatchNodeEditPanel.tsx','utf8');
describe('atomic batch node mutation',()=>{
 it('enforces authority, fixed search path, ACL and ledger isolation',()=>{for(const s of ['caller uuid:=auth.uid()','public.is_steward_or_overlord()','SECURITY DEFINER','SET search_path=public,pg_temp','REVOKE ALL ON FUNCTION public.admin_mutate_nodes_batch','GRANT EXECUTE ON FUNCTION public.admin_mutate_nodes_batch'])expect(SQL).toContain(s);expect(SQL).toContain('ENABLE ROW LEVEL SECURITY');expect(SQL).toContain('REVOKE TRUNCATE,REFERENCES,TRIGGER,MAINTAIN');expect(SQL).not.toContain('supabase_realtime');});
 it('allows only region and area and excludes connections, coordinates and IDs',()=>{expect(SQL).toContain("k NOT IN('region_id','area_id')");expect(SQL).toContain("'kind','unsupported_field'");const update=SQL.slice(SQL.indexOf('UPDATE public.nodes SET'),SQL.indexOf(' WHERE id=',SQL.indexOf('UPDATE public.nodes SET')));expect(update).not.toMatch(/connections=|\bx=|\by=|\bid=/);});
 it('validates nonempty unique canonically ordered batches capped at 100',()=>{expect(MAX_BATCH_NODES).toBe(100);expect(SQL).toContain('jsonb_array_length(_mutations)<1 OR jsonb_array_length(_mutations)>100');expect(SQL).toContain('cardinality(ids)<>cardinality(ARRAY(SELECT DISTINCT unnest(ids)))');expect(SQL).toContain("ids<>ARRAY(SELECT(e->>'node_id')::uuid");});
 it('supports one or many mutations in one rollback boundary',()=>{expect(SQL).toContain("FOR m IN SELECT value FROM jsonb_array_elements(_mutations)ORDER BY value->>'node_id' LOOP UPDATE public.nodes");expect(SQL).toContain("EXCEPTION WHEN OTHERS THEN response:=jsonb_build_object('ok',false,'kind','database_error')");});
 it('locks every node and referenced row deterministically after the request row',()=>{expect(SQL.indexOf('WHERE request_id=_request_id FOR UPDATE')).toBeLessThan(SQL.indexOf('WHERE id=ANY(ids)ORDER BY id FOR UPDATE'));expect(SQL.indexOf('WHERE id=ANY(ids)ORDER BY id FOR UPDATE')).toBeLessThan(SQL.indexOf('ORDER BY r.id FOR KEY SHARE'));expect(SQL.indexOf('ORDER BY r.id FOR KEY SHARE')).toBeLessThan(SQL.indexOf('ORDER BY a.id FOR KEY SHARE'));expect(SQL).toContain("ORDER BY value->>'node_id' LOOP UPDATE public.nodes");});
 it('compares complete canonical state and refuses the whole stale batch',()=>{expect(SQL).toContain("(to_jsonb(n)-'created_at')<>(m->'expected_state')");expect(SQL).toContain("'kind','stale_node_state','node_ids'");expect(SQL.indexOf("'kind','stale_node_state'")).toBeLessThan(SQL.indexOf('UPDATE public.nodes SET'));});
 it('validates region/area references and final consistency',()=>{expect(SQL).toContain("'kind','reference_not_found'");expect(SQL).toContain('a.id=final_area AND a.region_id=final_region');expect(SQL).toContain("'kind','inconsistent_region_area'");});
 it('fingerprints the canonical payload and provides replay/conflict behavior',()=>{expect(SQL).toContain('prior.mutations IS DISTINCT FROM _mutations');expect(SQL).toContain("'kind','request_conflict'");expect(SQL).toContain("jsonb_build_object('replayed',true)");let n=0;const t=createBatchNodeRequestTracker(()=>`r${++n}`);const first=t.requestIdFor('a');t.settle('a',true);expect(t.requestIdFor('a')).toBe(first);t.settle('a',false);expect(t.requestIdFor('a')).not.toBe(first);});
 it('protects unrelated fields in complete expected state',()=>{expect(batchNodeExpectedState({id:'n',created_at:'time',connections:[{future:true}],x:1,name:'N'})).toEqual({id:'n',connections:[{future:true}],x:1,name:'N'});});
 it('uses only the RPC with duplicate/stale fencing and explicit unchanged/null language',()=>{expect(UI).toContain('submitBatchNodeMutations(');expect(UI).not.toContain(".from('nodes')");expect(UI).toContain('saveFence.current.tryAcquire()');expect(UI).toContain('saveFence.current.release(operation)');expect(UI).toContain('refresh before retrying');expect(UI).toContain('all-or-nothing');expect(UI).toContain('“Clear area” writes no area');});
 it('strictly decodes success and refusal results',()=>{expect(decodeBatchNodeResult({ok:true,kind:'updated',updated_count:2,replayed:false})).not.toBeNull();expect(decodeBatchNodeResult({ok:false,kind:'stale_node_state',node_ids:['a']})).not.toBeNull();expect(decodeBatchNodeResult({ok:true,kind:'updated',updated_count:'2',replayed:false})).toBeNull();});
});
