/**
 * Shared combat/effect resolver — single source of truth for:
 * - DoT/effect tick processing
 * - Creature HP writes
 * - Effect cleanup
 * - Loot drops
 *
 * Used by both `combat-tick` and `combat-catchup` edge functions.
 *
 * ## Architecture
 *
 * The `active_effects` table is the **sole authoritative store** for all DoT/
 * status-effect state. Combat sessions (`combat_sessions`) track only timing
 * and engagement — never effect data.
 *
 * Time advances in **deterministic discrete steps**: `next_tick_at += tick_rate_ms`.
 * This prevents wall-clock drift regardless of when the server processes a tick.
 *
 * Two processing modes exist:
 * - **Single-tick** (`tickTime` provided): used by `combat-tick` once per 2 s
 *   heartbeat inside its tick loop. Checks one point in time.
 * - **Bulk mode** (`now` provided, no `tickTime`): used by `combat-catchup` on
 *   node entry. Retroactively processes all elapsed ticks up to `tickCap`.
 *
 * The server is authoritative — client UI reflects returned state, never
 * assumes local truth for effect data.
 */

// ── Types ────────────────────────────────────────────────────────

export interface LootQueueEntry {
  nodeId: string;
  lootTableId: string | null;
  itemId: string | null;
  creatureName: string;
  dropChance: number;
  mode: 'legacy' | 'item_pool';
  creatureLevel?: number;
}

export interface EffectTickResult {
  /** Effect IDs that should be deleted (expired or target killed) */
  expiredIds: string[];
  /** Creature IDs killed by effects this resolution */
  newKills: Set<string>;
  /** Loot queue entries generated by effect kills */
  lootQueue: LootQueueEntry[];
  /** Events/messages generated during processing */
  events: { type: string; message: string }[];
  /** Cleared DoT info for client sync */
  clearedDots: { character_id: string; creature_id: string; dot_type: string }[];
  /** Effects whose next_tick_at was advanced (for DB upsert) */
  advancedEffects: any[];
}

// ── resolveEffectTicks ───────────────────────────────────────────
/**
 * Process active effects against creature HP.
 *
 * **Single-tick mode** (`tickTime` provided): process effects due at that
 * specific tick timestamp. Used by `combat-tick` once per tick inside its loop.
 *
 * **Bulk mode** (`tickTime` omitted, `now` required): calculate all elapsed
 * ticks per effect and process them all. Used by `combat-catchup` on node entry.
 *
 * @param effects       In-memory active_effects rows for this node
 * @param cHp           Mutable creature HP map (updated in place)
 * @param cKilled       Mutable set of already-killed creature IDs
 * @param creatures     Full creature rows (for loot info on kill)
 * @param tickCap       Max ticks per effect in bulk mode
 * @param opts.tickTime If set, single-tick mode at this timestamp
 * @param opts.now      Current wall-clock ms (required for bulk mode)
 * @param opts.memberNameMap  Map of source_id → character name for messages
 */
export function resolveEffectTicks(
  effects: any[],
  cHp: Record<string, number>,
  cKilled: Set<string>,
  creatures: any[],
  tickCap: number,
  opts: {
    tickTime?: number;
    now?: number;
    memberNameMap?: Record<string, string>;
  } = {},
): EffectTickResult {
  const { tickTime, now, memberNameMap } = opts;
  const isSingleTick = tickTime !== undefined;

  const expiredIds: string[] = [];
  const newKills = new Set<string>();
  const lootQueue: LootQueueEntry[] = [];
  const events: { type: string; message: string }[] = [];
  const clearedDots: { character_id: string; creature_id: string; dot_type: string }[] = [];
  const advancedEffects: any[] = [];

  for (const eff of effects) {
    // Skip effects on already-dead targets
    if (cKilled.has(eff.target_id) || cHp[eff.target_id] === undefined || cHp[eff.target_id] <= 0) {
      if (!cKilled.has(eff.target_id) && cHp[eff.target_id] !== undefined) {
        // HP is 0 but not in killed set — skip
      }
      continue;
    }

    const creature = creatures.find((cr: any) => cr.id === eff.target_id);
    if (!creature) continue;

    const charName = memberNameMap?.[eff.source_id] || 'Unknown';

    if (isSingleTick) {
      // ── Single-tick mode ─────────────────────────────────────
      // Check expiry
      if (eff.expires_at <= tickTime!) {
        eff._expired = true;
        expiredIds.push(eff.id);
        clearedDots.push({ character_id: eff.source_id, creature_id: eff.target_id, dot_type: eff.effect_type });
        continue;
      }

      // Apply tick if due
      if (eff.next_tick_at <= tickTime!) {
        const totalDmg = (eff.effect_type === 'bleed') ? eff.damage_per_tick : eff.stacks * eff.damage_per_tick;
        cHp[eff.target_id] = Math.max(cHp[eff.target_id] - totalDmg, 0);

        const emoji = eff.effect_type === 'bleed' ? '🩸' : eff.effect_type === 'poison' ? '🧪' : '🔥';
        const verb = eff.effect_type === 'bleed' ? 'bleeds' : eff.effect_type === 'poison' ? 'takes' : 'burns';
        const suffix = eff.effect_type === 'bleed'
          ? `(${charName}'s Rend)`
          : `(${eff.stacks} stack${eff.stacks > 1 ? 's' : ''}, ${charName})`;
        const dmgLabel = eff.effect_type === 'bleed' ? eff.damage_per_tick : totalDmg;
        const dmgType = eff.effect_type === 'bleed' ? '' : eff.effect_type === 'poison' ? ' poison' : ' fire';
        events.push({ type: 'dot_tick', message: `${emoji} ${creature.name} ${verb} for ${dmgLabel}${dmgType} damage! ${suffix}` });

        eff.next_tick_at += eff.tick_rate_ms;
        advancedEffects.push(eff);

        if (cHp[eff.target_id] <= 0 && !cKilled.has(eff.target_id)) {
          cKilled.add(eff.target_id);
          newKills.add(eff.target_id);
          pushCreatureLoot(creature, eff.target_id, lootQueue);
        }
      }
    } else {
      // ── Bulk mode ────────────────────────────────────────────
      const currentNow = now!;
      const elapsedMs = currentNow - eff.next_tick_at;
      if (elapsedMs < 0) continue; // Not due yet

      const ticksToProcess = Math.floor(elapsedMs / eff.tick_rate_ms) + 1;
      const maxTicksByExpiry = Math.max(0, Math.floor((eff.expires_at - eff.next_tick_at) / eff.tick_rate_ms) + 1);
      const ticks = Math.min(ticksToProcess, tickCap, maxTicksByExpiry);

      if (ticks <= 0) {
        if (currentNow >= eff.expires_at) expiredIds.push(eff.id);
        continue;
      }

      for (let t = 0; t < ticks; t++) {
        const tt = eff.next_tick_at + t * eff.tick_rate_ms;
        if (tt > eff.expires_at) break;
        if (cKilled.has(eff.target_id) || cHp[eff.target_id] <= 0) break;

        const totalDmg = (eff.effect_type === 'bleed') ? eff.damage_per_tick : eff.stacks * eff.damage_per_tick;
        cHp[eff.target_id] = Math.max(cHp[eff.target_id] - totalDmg, 0);

        if (cHp[eff.target_id] <= 0 && !cKilled.has(eff.target_id)) {
          cKilled.add(eff.target_id);
          newKills.add(eff.target_id);
          pushCreatureLoot(creature, eff.target_id, lootQueue);
        }
      }

      const newNextTickAt = eff.next_tick_at + ticks * eff.tick_rate_ms;
      if (newNextTickAt >= eff.expires_at || cKilled.has(eff.target_id)) {
        expiredIds.push(eff.id);
      } else {
        eff.next_tick_at = newNextTickAt;
        advancedEffects.push(eff);
      }
    }
  }

  return { expiredIds, newKills, lootQueue, events, clearedDots, advancedEffects };
}

// ── Helper: push loot queue entries for a killed creature ─────────
function pushCreatureLoot(creature: any, _creatureId: string, lootQueue: LootQueueEntry[]) {
  const nodeId = creature.node_id;
  const lootMode = creature.loot_mode || 'legacy_table';

  // item_pool mode — delegate to processLootDrops for DB-based pool resolution
  if (lootMode === 'item_pool') {
    lootQueue.push({
      nodeId,
      lootTableId: null,
      itemId: null,
      creatureName: creature.name,
      dropChance: creature.drop_chance ?? 0.5,
      mode: 'item_pool',
      creatureLevel: creature.level,
    });
    return;
  }

  // salvage_only — no item loot
  if (lootMode === 'salvage_only') return;

  // legacy_table mode
  if (creature.loot_table_id) {
    lootQueue.push({
      nodeId,
      lootTableId: creature.loot_table_id,
      itemId: null,
      creatureName: creature.name,
      dropChance: creature.drop_chance ?? 0.5,
      mode: 'legacy',
    });
  } else {
    const lt = (creature.loot_table || []) as any[];
    for (const entry of lt) {
      if (entry.type === 'gold') continue;
      if (Math.random() <= (entry.chance || 0.1)) {
        lootQueue.push({
          nodeId,
          lootTableId: null,
          itemId: entry.item_id,
          creatureName: creature.name,
          dropChance: 1,
          mode: 'legacy',
        });
      }
    }
  }
}

// ── processLootDrops ─────────────────────────────────────────────
/**
 * Resolve loot table entries, handle unique-item deduplication,
 * and insert ground loot. Returns loot event messages.
 */
export async function processLootDrops(
  db: any,
  lootQueue: LootQueueEntry[],
): Promise<{ type: string; message: string }[]> {
  const events: { type: string; message: string }[] = [];

  // Cache pool config for item_pool drops
  let poolConfig: any = null;

  for (const drop of lootQueue) {
    try {
      // ── item_pool mode ──────────────────────────────────────────
      if (drop.mode === 'item_pool') {
        if (Math.random() > drop.dropChance) continue;

        // Lazy-load pool config
        if (!poolConfig) {
          const { data } = await db.from('loot_pool_config').select('*').eq('id', 1).single();
          poolConfig = data || { equip_level_min_offset: -3, equip_level_max_offset: 0, common_pct: 80, uncommon_pct: 20, consumable_drop_chance: 0.15, consumable_level_min_offset: -5, consumable_level_max_offset: 0 };
        }

        const creatureLevel = drop.creatureLevel || 1;

        // Roll equipment
        const rarityRoll = Math.random() * 100;
        const rolledRarity = rarityRoll < poolConfig.common_pct ? 'common' : 'uncommon';

        const minLevel = creatureLevel + poolConfig.equip_level_min_offset;
        const maxLevel = creatureLevel + poolConfig.equip_level_max_offset;

        const { data: eligible } = await db
          .from('items')
          .select('id, name, rarity, drop_weight')
          .eq('world_drop', true)
          .eq('rarity', rolledRarity)
          .eq('item_type', 'equipment')
          .eq('is_soulbound', false)
          .gte('level', minLevel)
          .lte('level', maxLevel);

        if (eligible && eligible.length > 0) {
          // Weighted random
          const totalW = eligible.reduce((s: number, e: any) => s + (e.drop_weight || 10), 0);
          let r = Math.random() * totalW;
          let picked = eligible[eligible.length - 1];
          for (const e of eligible) {
            r -= (e.drop_weight || 10);
            if (r <= 0) { picked = e; break; }
          }

          await db.from('node_ground_loot').insert({
            node_id: drop.nodeId,
            item_id: picked.id,
            creature_name: drop.creatureName,
          });
          events.push({ type: 'loot_drop', message: `💎 ${drop.creatureName} dropped ${picked.name}!` });
        }

        // Separate consumable roll
        if (Math.random() < poolConfig.consumable_drop_chance) {
          const cMinLevel = creatureLevel + poolConfig.consumable_level_min_offset;
          const cMaxLevel = creatureLevel + poolConfig.consumable_level_max_offset;

          const { data: consumables } = await db
            .from('items')
            .select('id, name, drop_weight')
            .eq('world_drop', true)
            .eq('item_type', 'consumable')
            .gte('level', cMinLevel)
            .lte('level', cMaxLevel);

          if (consumables && consumables.length > 0) {
            const totalCW = consumables.reduce((s: number, e: any) => s + (e.drop_weight || 10), 0);
            let cr = Math.random() * totalCW;
            let pickedC = consumables[consumables.length - 1];
            for (const e of consumables) {
              cr -= (e.drop_weight || 10);
              if (cr <= 0) { pickedC = e; break; }
            }

            await db.from('node_ground_loot').insert({
              node_id: drop.nodeId,
              item_id: pickedC.id,
              creature_name: drop.creatureName,
            });
            events.push({ type: 'loot_drop', message: `🧴 ${drop.creatureName} dropped ${pickedC.name}!` });
          }
        }

        continue;
      }

      // ── legacy mode ─────────────────────────────────────────────
      let pickedItemId: string | null = null;

      if (drop.lootTableId) {
        if (Math.random() > drop.dropChance) continue;
        const { data: entries } = await db
          .from('loot_table_entries')
          .select('item_id, weight')
          .eq('loot_table_id', drop.lootTableId);
        if (!entries || entries.length === 0) continue;
        const totalW = entries.reduce((s: number, e: any) => s + e.weight, 0);
        let r = Math.random() * totalW;
        for (const e of entries) {
          r -= e.weight;
          if (r <= 0) { pickedItemId = e.item_id; break; }
        }
        if (!pickedItemId) pickedItemId = entries[entries.length - 1].item_id;
      } else if (drop.itemId) {
        pickedItemId = drop.itemId;
      }

      if (!pickedItemId) continue;

      const { data: item } = await db.from('items').select('name, rarity').eq('id', pickedItemId).single();
      if (!item) continue;

      if (item.rarity === 'unique') {
        const { count } = await db
          .from('character_inventory')
          .select('id', { count: 'exact', head: true })
          .eq('item_id', pickedItemId);
        if (count && count > 0) {
          events.push({ type: 'loot_drop', message: `✨ The unique power of ${item.name} is already claimed...` });
          continue;
        }
      }

      await db.from('node_ground_loot').insert({
        node_id: drop.nodeId,
        item_id: pickedItemId,
        creature_name: drop.creatureName,
      });
      events.push({ type: 'loot_drop', message: `💎 ${drop.creatureName} dropped ${item.name}!` });
    } catch (e) {
      console.error('Loot drop error:', e);
    }
  }

  return events;
}

// ── writeCreatureState ───────────────────────────────────────────
/**
 * Persist creature HP changes and kills via the `damage_creature` RPC.
 */
export async function writeCreatureState(
  db: any,
  creatures: any[],
  cHp: Record<string, number>,
  cKilled: Set<string>,
): Promise<void> {
  const promises = creatures.map((cr) => {
    if (cKilled.has(cr.id)) {
      return db.rpc('damage_creature', { _creature_id: cr.id, _new_hp: 0, _killed: true });
    } else if (cHp[cr.id] !== cr.hp) {
      return db.rpc('damage_creature', { _creature_id: cr.id, _new_hp: cHp[cr.id] });
    }
    return Promise.resolve();
  });
  await Promise.all(promises);
}

// ── cleanupEffects ───────────────────────────────────────────────
/**
 * Delete expired effects and all effects targeting killed creatures.
 */
export async function cleanupEffects(
  db: any,
  expiredIds: string[],
  killedCreatureIds: Set<string>,
): Promise<void> {
  if (killedCreatureIds.size > 0) {
    await db.from('active_effects').delete().in('target_id', [...killedCreatureIds]);
  }
  // Delete expired effects (some may overlap with killed-target deletes, that's fine)
  if (expiredIds.length > 0) {
    await db.from('active_effects').delete().in('id', expiredIds);
  }
}
