import { supabase } from '@/integrations/supabase/client';

export const MAX_BATCH_NODES=100;
export type BatchNodeResult=|{ok:true;kind:'updated';updated_count:number;replayed:boolean}|{ok:false;kind:'not_authenticated'|'not_authorized'|'invalid_request'|'request_conflict'|'node_not_found'|'stale_node_state'|'unsupported_field'|'reference_not_found'|'inconsistent_region_area'|'database_error'|'transport_error'|'malformed_response';node_ids?:string[]};
const refusals=new Set(['not_authenticated','not_authorized','invalid_request','request_conflict','node_not_found','stale_node_state','unsupported_field','reference_not_found','inconsistent_region_area','database_error']);
export function decodeBatchNodeResult(value:unknown):BatchNodeResult|null{if(!value||typeof value!=='object')return null;const r=value as Record<string,unknown>;if(r.ok===true&&r.kind==='updated'&&Number.isInteger(r.updated_count)&&typeof r.replayed==='boolean')return r as BatchNodeResult;if(r.ok===false&&typeof r.kind==='string'&&refusals.has(r.kind)&&(!('node_ids'in r)||(Array.isArray(r.node_ids)&&r.node_ids.every(x=>typeof x==='string'))))return r as BatchNodeResult;return null;}
export function batchNodeExpectedState(node:Record<string,unknown>){const{created_at:_created,...state}=node;return state;}
export function createBatchNodeRequestTracker(make:()=>string=()=>crypto.randomUUID()){let retry:{fingerprint:string;id:string}|null=null;return{requestIdFor(f:string){if(retry?.fingerprint===f)return retry.id;retry={fingerprint:f,id:make()};return retry.id;},settle(f:string,retryable:boolean){if(!retryable&&retry?.fingerprint===f)retry=null;}};}
export async function submitBatchNodeMutations(mutations:unknown[],tracker:ReturnType<typeof createBatchNodeRequestTracker>):Promise<BatchNodeResult>{const ordered=[...mutations].sort((a:any,b:any)=>String(a.node_id).localeCompare(String(b.node_id)));const fingerprint=JSON.stringify(ordered);const{data,error}=await supabase.rpc('admin_mutate_nodes_batch' as never,{_request_id:tracker.requestIdFor(fingerprint),_mutations:ordered}as never);const result:BatchNodeResult=error?{ok:false,kind:'transport_error'}:decodeBatchNodeResult(data)??{ok:false,kind:'malformed_response'};tracker.settle(fingerprint,!result.ok&&result.kind==='transport_error');return result;}
