import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, RefreshCw, ShieldAlert } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { supabase } from '@/integrations/supabase/client';
import { COMBAT2_TEST_ARENA, createArenaAdminApi, type ArenaApiResult, type ArenaStatus, type TestRunReport } from '@/features/combat2-test-arena/admin-api';
import type { AdminUser } from '@/components/admin/users/constants';

const api=createArenaAdminApi();
const nodeLabels:Record<string,string>=Object.fromEntries(COMBAT2_TEST_ARENA.nodes.map(node=>[node.purpose,node.label]));
const shorten=(id:string)=>`${id.slice(0,8)}…${id.slice(-4)}`;
const operationText=(value:{ok:boolean;kind:string;stage?:string;code?:string})=>`${value.ok?'Accepted':'Refused'}: ${value.kind}${value.stage?` at ${value.stage}${value.code?` (${value.code})`:''}`:''}`;
export const arenaReportEventText=(event:Record<string,unknown>)=>{const actor=typeof event.actor==='object'&&event.actor&&'name' in event.actor?String((event.actor as {name?:unknown}).name??'Unknown'):'System';const target=typeof event.target==='object'&&event.target&&'name' in event.target?String((event.target as {name?:unknown}).name??'unknown target'):'';const ability=typeof event.abilityKey==='string'?` ${event.abilityKey.replaceAll('_',' ')}`:'';const amount=typeof event.amount==='number'?` (${event.amount})`:'';const meta=event.meta&&typeof event.meta==='object'&&!Array.isArray(event.meta)?event.meta as Record<string,unknown>:{};const detail=['requested','applied','wasted','hpRequested','hpApplied','hpWasted','cpRequested','cpApplied','cpWasted','removedFromCaster','remaining','depleted'].flatMap(key=>meta[key]===undefined?[]:[`${key}=${String(meta[key])}`]);return `${actor}: ${String(event.kind??'event')}${ability}${target?` → ${target}`:''}${amount}${detail.length?` [${detail.join(', ')}]`:''}`;};

export default function Combat2TestArenaPanel(){
 const [status,setStatus]=useState<ArenaStatus|null>(null);const [report,setReport]=useState<TestRunReport|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
 const [users,setUsers]=useState<AdminUser[]>([]);const [userId,setUserId]=useState('');const [characterId,setCharacterId]=useState('');const [nodeId,setNodeId]=useState('');const [busy,setBusy]=useState<string|null>(null);const [result,setResult]=useState('');const [refreshedAt,setRefreshedAt]=useState<Date|null>(null);const [resetPhrase,setResetPhrase]=useState('');
 const runStartRequest=useRef<string|null>(null);const runStopRequest=useRef<string|null>(null);const emergencyStopRequest=useRef<string|null>(null);const resetRequest=useRef<string|null>(null);const environmentStartRequest=useRef<string|null>(null);const environmentCloseRequest=useRef<string|null>(null);const mounted=useRef(true);const busyRef=useRef(false);const refreshVersion=useRef(0);const selection=useRef('');
 const selectedUser=users.find(u=>u.id===userId);const characters=selectedUser?.characters??[];const selectedCharacter=characters.find(c=>c.id===characterId);const access=status?.access.find(a=>a.userId===userId&&a.characterId===characterId);const recording=report?.status==='recording';
 const loadReport=useCallback(async(runId:string|null,afterSeq=0,append=false)=>{const version=++refreshVersion.current;const response=await api.report(runId,afterSeq,25);if(!mounted.current||version!==refreshVersion.current)return;if(response.value)setReport(previous=>append&&previous&&previous.runId===response.value!.runId?{...response.value!,batches:[...previous.batches,...response.value!.batches]}:response.value!);},[]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');const response=await api.status();if(!mounted.current)return;if(response.value){setStatus(response.value);setRefreshedAt(new Date());const staging=response.value.nodes.find(n=>n.purpose==='staging');setNodeId(current=>current||staging?.id||'');await loadReport(report?.runId??null);}else setError(response.error??'Status refused.');if(mounted.current)setLoading(false);},[loadReport,report?.runId]);
 useEffect(()=>{mounted.current=true;void refresh();void(async()=>{try{const {data:{session}}=await supabase.auth.getSession();if(!session)return;const response=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/admin-users?action=list&page=1`,{headers:{Authorization:`Bearer ${session.access_token}`,apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY}});const body=await response.json();if(mounted.current&&response.ok&&Array.isArray(body.users))setUsers(body.users);}catch{if(mounted.current)setError('Admin user list unavailable.');}})();return()=>{mounted.current=false;};},[]);
 useEffect(()=>{setCharacterId(characters[0]?.id??'');},[userId]);useEffect(()=>{selection.current=`${userId}:${characterId}`;setResult('');},[userId,characterId]);
 const mutate=async<T extends {ok:boolean;kind:string;stage?:string;code?:string}>(name:string,run:()=>Promise<ArenaApiResult<T>>,stable?:React.MutableRefObject<string|null>)=>{if(busyRef.current)return;busyRef.current=true;const snapshot=selection.current;setBusy(name);setResult('');try{const response=await run();if(!mounted.current||snapshot!==selection.current)return;if(response.value){setResult(operationText(response.value));if(stable&&!response.uncertain)stable.current=null;await refresh();}else{setResult(response.error??'Request failed.');if(stable&&!response.uncertain)stable.current=null;}}catch{if(mounted.current&&snapshot===selection.current)setResult('Request failed.');}finally{busyRef.current=false;if(mounted.current)setBusy(null);}};
 const idFor=(ref:React.MutableRefObject<string|null>)=>ref.current??(ref.current=crypto.randomUUID());const activeNodeOptions=useMemo(()=>status?.nodes.filter(n=>n.active)??[],[status]);const summaryEntries=Object.entries(report?.summary??{});

 return <div className="h-full overflow-auto p-4 md:p-6"><div className="space-y-4"><header><h1 className="font-display text-2xl text-primary">Combat2 Test Arena</h1><p className="text-sm text-muted-foreground">Record a diagnostic run without implicitly changing the global Combat2 environment.</p></header>
  <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-2">
   <main className="order-2 min-w-0 space-y-4 lg:order-1">
    <Card><CardHeader><CardTitle>Diagnostic recording</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="text-base font-medium">{recording?'Recording':report?.status==='completed'?'Completed':'Not recording'}</p>{report&&<p>Run {shorten(report.runId)} · started {new Date(report.startedAt).toLocaleString()}</p>}{!status?.schedulerEnabled&&<p role="status" className="text-amber-700 dark:text-amber-300">The global environment is closed. Use Advanced environment controls before expecting scheduled ticks.</p>}<div className="flex flex-wrap gap-2"><Button disabled={!status||status.locatedTesterCount<1||recording||!!busy} onClick={()=>mutate('run-start',()=>api.startRun(idFor(runStartRequest)),runStartRequest)}>Start recording</Button><AlertDialog><AlertDialogTrigger asChild><Button variant="outline" disabled={!recording||!!busy}>Stop and generate report</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Stop recording and freeze this report?</AlertDialogTitle><AlertDialogDescription>Arena encounters will be stopped and fenced. Global combat, world and scheduler state remain unchanged.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>mutate('run-stop',()=>api.stopRun(idFor(runStopRequest)),runStopRequest)}>Confirm stop</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></CardContent></Card>
	    <Card><CardHeader><CardTitle>Tester access and relocation</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="grid gap-2 md:grid-cols-2"><label>User<select aria-label="Test user" className="w-full rounded border bg-background p-2" value={userId} onChange={e=>setUserId(e.target.value)}><option value="">Select existing user</option>{users.map(u=><option key={u.id} value={u.id}>{u.profile?.display_name||u.id}</option>)}</select></label><label>Owned character<select aria-label="Owned character" className="w-full rounded border bg-background p-2" value={characterId} onChange={e=>setCharacterId(e.target.value)} disabled={!userId}><option value="">Select owned character</option>{characters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>{selectedCharacter&&<p><b>{selectedCharacter.name}</b> · access {access?.active&&!access.revoked?'active':access?.revoked?'revoked':'absent'}</p>}<div className="flex flex-wrap gap-2"><Button size="sm" disabled={!selectedCharacter||!!busy} onClick={()=>mutate('grant',()=>api.grant(userId,characterId))}>Grant exact access</Button><Button size="sm" variant="outline" disabled={!selectedCharacter||!!busy} onClick={()=>mutate('revoke',()=>api.revoke(userId,characterId))}>Revoke exact access</Button></div><div className="flex flex-wrap items-end gap-2"><label className="min-w-56 flex-1">Registered destination<select aria-label="Arena destination" className="w-full rounded border bg-background p-2" value={nodeId} onChange={e=>setNodeId(e.target.value)}>{activeNodeOptions.map(n=><option key={n.id} value={n.id}>{nodeLabels[n.purpose]}</option>)}</select></label><Button disabled={!selectedCharacter||!access?.active||access.revoked||!nodeId||!!busy} onClick={()=>mutate('relocate',()=>api.relocate(characterId,nodeId))}>Relocate tester</Button></div></CardContent></Card>
    <Card className="border-destructive/50"><CardHeader><CardTitle className="flex items-center gap-2 text-destructive"><ShieldAlert className="h-5 w-5"/>Reset arena</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Deletes arena runtime diagnostics and restores registered testers and creatures. Completed Test Reports remain available.</p><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" disabled={recording||!status?.resetEligible||!!busy}>Reset arena</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle><AlertTriangle className="mr-2 inline h-5 w-5"/>Destroy arena runtime diagnostics?</AlertDialogTitle><AlertDialogDescription>A recording must be stopped first. Type {COMBAT2_TEST_ARENA.resetPhrase}.</AlertDialogDescription></AlertDialogHeader><Input aria-label="Reset confirmation" value={resetPhrase} onChange={e=>setResetPhrase(e.target.value)}/><AlertDialogFooter><AlertDialogCancel onClick={()=>setResetPhrase('')}>Cancel</AlertDialogCancel><AlertDialogAction disabled={resetPhrase!==COMBAT2_TEST_ARENA.resetPhrase} onClick={()=>{setResetPhrase('');void mutate('reset',()=>api.reset(idFor(resetRequest)),resetRequest);}}>Confirm destructive reset</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></CardContent></Card>
    <details className="rounded-lg border bg-card p-4"><summary className="cursor-pointer font-semibold">Advanced environment controls</summary><div className="mt-3 space-y-3 text-sm"><p>These global controls are operational prerequisites, not part of diagnostic recording.</p><div className="flex flex-wrap gap-2"><Button disabled={!status||status.locatedTesterCount<1||!!busy} onClick={()=>mutate('environment-start',()=>api.startEnvironment(idFor(environmentStartRequest)),environmentStartRequest)}>Start test environment</Button><Button variant="outline" disabled={!status||!!busy} onClick={()=>mutate('environment-close',()=>api.closeEnvironment(idFor(environmentCloseRequest)),environmentCloseRequest)}>Close test environment safely</Button><Button variant="outline" disabled={!status||!!busy} onClick={()=>mutate('emergency-stop',()=>api.stop(idFor(emergencyStopRequest)),emergencyStopRequest)}>Emergency arena stop</Button></div></div></details>{result&&<p role="status" className="rounded border p-3 text-sm">{result}</p>}
   </main>
   <aside className="order-1 min-w-0 space-y-4 lg:sticky lg:top-4 lg:order-2"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Arena status</CardTitle><Button variant="outline" size="sm" onClick={()=>void refresh()} disabled={loading}><RefreshCw className="mr-1 h-4 w-4"/>Refresh</Button></CardHeader><CardContent className="space-y-2 text-sm">{loading&&<p>Loading authoritative status…</p>}{error&&<p role="alert" className="text-destructive">{error}</p>}{status&&<><p><b>{status.label}</b> · {status.stopped?'stopped':'running'}</p><p>Recording: <b>{recording?'yes':'no'}</b>{report?` · ${shorten(report.runId)}`:''}</p><p>{status.activeEncounterCount} encounters · {status.claimedEncounterCount} claims</p><p>Combat {status.combatMode} · world {status.worldState} · scheduler {status.schedulerEnabled?'enabled':'disabled'}</p><p>Reset eligible: {status.resetEligible&&!recording?'yes':'no'}</p></>}<p className="text-xs text-muted-foreground">Manual refresh: {refreshedAt?.toLocaleTimeString()??'never'}</p></CardContent></Card>
	    <Card className="min-w-0 overflow-hidden"><CardHeader><CardTitle>Test Report</CardTitle></CardHeader><CardContent className="min-w-0 space-y-3 text-sm">{!report?<p className="text-muted-foreground">No diagnostic run is available.</p>:<><p className="break-words"><b>{report.status}</b> · {new Date(report.startedAt).toLocaleString()}{report.completedAt?` – ${new Date(report.completedAt).toLocaleString()}`:''}</p><div className="grid min-w-0 grid-cols-2 gap-2">{summaryEntries.map(([key,value])=><div key={key} className="min-w-0 rounded border p-2"><div className="break-words text-xs text-muted-foreground">{key.replaceAll('_',' ')}</div><b>{value}</b></div>)}</div><ol className="min-w-0 max-h-80 space-y-1 overflow-auto" aria-label="Ordered combat report">{report.batches.flatMap(batch=>batch.events.map((event,index)=><li key={`${batch.seq}-${index}`} className="min-w-0 break-words border-l-2 pl-2"><span className="text-xs text-muted-foreground">#{batch.seq}/tick {batch.tick}</span> {arenaReportEventText(event)}</li>))}</ol>{report.hasMore&&<Button variant="outline" size="sm" onClick={()=>void loadReport(report.runId,report.returnedThroughSeq,true)}>Load more</Button>}</>}</CardContent></Card></aside>
  </div>
 </div></div>;
}
