import {useCallback,useEffect,useRef,useState} from 'react';
import {AlertTriangle,RefreshCw,ShieldAlert} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from '@/components/ui/alert-dialog';
import {COMBAT2_TEST_ARENA,createArenaAdminApi,type ArenaApiResult,type ArenaStatus,type TestRunReport,type TestRunResult} from '@/features/combat2-test-arena/admin-api';

const api=createArenaAdminApi();
const shorten=(id:string)=>`${id.slice(0,8)}…${id.slice(-4)}`;
const operationText=(v:{ok:boolean;kind:string;stage?:string;code?:string})=>`${v.ok?'Accepted':'Refused'}: ${v.kind}${v.stage?` at ${v.stage}${v.code?` (${v.code})`:''}`:''}`;
export const arenaReportEventText=(event:Record<string,unknown>)=>{const actor=typeof event.actor==='object'&&event.actor&&'name' in event.actor?String((event.actor as {name?:unknown}).name??'Unknown'):'System';const target=typeof event.target==='object'&&event.target&&'name' in event.target?String((event.target as {name?:unknown}).name??'unknown target'):'';const ability=typeof event.abilityKey==='string'?` ${event.abilityKey.replaceAll('_',' ')}`:'';const amount=typeof event.amount==='number'?` (${event.amount})`:'';return `${actor}: ${String(event.kind??'event')}${ability}${target?` → ${target}`:''}${amount}`;};

export default function Combat2TestArenaPanel(){
 const [status,setStatus]=useState<ArenaStatus|null>(null);const [report,setReport]=useState<TestRunReport|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [result,setResult]=useState('');const [resetPhrase,setResetPhrase]=useState('');
 const mounted=useRef(true);const busyRef=useRef(false);const refreshVersion=useRef(0);const runStartRequest=useRef<string|null>(null);const runStopRequest=useRef<string|null>(null);const resetRequest=useRef<string|null>(null);const emergencyRequest=useRef<string|null>(null);
 const recording=report?.status==='recording';
 const loadReport=useCallback(async(runId:string|null,afterSeq=0,append=false)=>{const version=++refreshVersion.current;const response=await api.report(runId,afterSeq,25);if(!mounted.current||version!==refreshVersion.current)return;if(response.value)setReport(previous=>{if(previous?.status==='completed'&&response.value!.runId===previous.runId&&response.value!.status==='recording')return previous;return append&&previous&&previous.runId===response.value!.runId?{...response.value!,batches:[...previous.batches,...response.value!.batches]}:response.value!;});else if(response.error)setError(response.error);},[]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');const response=await api.status();if(!mounted.current)return;if(response.value){setStatus(response.value);await loadReport(report?.runId??null);}else setError(response.error??'Status refused.');if(mounted.current)setLoading(false);},[loadReport,report?.runId]);
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;};},[]);
 const idFor=(ref:React.MutableRefObject<string|null>)=>ref.current??(ref.current=crypto.randomUUID());
 const mutate=async<T extends {ok:boolean;kind:string;stage?:string;code?:string}>(name:string,run:()=>Promise<ArenaApiResult<T>>,stable:React.MutableRefObject<string|null>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(name);setResult('');try{const response=await run();if(!mounted.current)return;if(response.value){setResult(operationText(response.value));if(name==='run-stop'){const stopped=response.value as unknown as TestRunResult;if(stopped.status==='completed')setReport(previous=>previous&&previous.runId===stopped.runId?{...previous,status:'completed',completedAt:stopped.completedAt,latestSeq:stopped.latestSeq??previous.latestSeq,summary:stopped.summary??previous.summary}:previous);}if(!response.uncertain)stable.current=null;void refresh();}else{setResult(response.error??'Request failed.');if(!response.uncertain)stable.current=null;}}finally{busyRef.current=false;if(mounted.current)setBusy(null);}};
 const summaryEntries=Object.entries(report?.summary??{});
 return <div className="h-full overflow-auto p-4 md:p-6"><div className="space-y-4"><header><h1 className="font-display text-2xl text-primary">Combat2 Test Arena</h1><p className="text-sm text-muted-foreground">Arena processing wakes automatically for authorized testers and sleeps after inactivity.</p></header><div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-2">
  <main className="order-2 min-w-0 space-y-4 lg:order-1"><Card><CardHeader><CardTitle>Diagnostic recording</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="text-base font-medium">{recording?'Recording':report?.status==='completed'?'Completed':'Not recording'}</p><div className="flex gap-2"><Button disabled={recording||!!busy} onClick={()=>mutate('run-start',()=>api.startRun(idFor(runStartRequest)),runStartRequest)}>Start Recording</Button><Button variant="outline" disabled={!recording||!!busy} onClick={()=>mutate('run-stop',()=>api.stopRun(idFor(runStopRequest)),runStopRequest)}>Stop Recording and generate report</Button></div></CardContent></Card>
  <Card className="border-destructive/50"><CardHeader><CardTitle className="flex items-center gap-2 text-destructive"><ShieldAlert className="h-5 w-5"/>Safety controls</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive" disabled={recording||!status?.resetEligible||status.activePresenceCount>0||status.arenaLiveClaimCount>0||!!busy}>Reset Arena</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle><AlertTriangle className="mr-2 inline h-5 w-5"/>Reset arena?</AlertDialogTitle><AlertDialogDescription>Type {COMBAT2_TEST_ARENA.resetPhrase}. Completed reports are preserved.</AlertDialogDescription></AlertDialogHeader><Input aria-label="Reset confirmation" value={resetPhrase} onChange={e=>setResetPhrase(e.target.value)}/><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction disabled={resetPhrase!==COMBAT2_TEST_ARENA.resetPhrase} onClick={()=>{setResetPhrase('');void mutate('reset',()=>api.reset(idFor(resetRequest)),resetRequest);}}>Confirm reset</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Button variant="destructive" disabled={!!busy} onClick={()=>mutate('emergency',()=>api.emergencyShutdown(idFor(emergencyRequest)),emergencyRequest)}>Emergency Shutdown</Button></CardContent></Card>{result&&<p role="status" className="rounded border p-3 text-sm">{result}</p>}</main>
  <aside className="order-1 min-w-0 space-y-4 lg:sticky lg:top-4 lg:order-2"><Card><CardHeader className="flex-row items-center justify-between"><CardTitle>Current state</CardTitle><Button variant="outline" size="sm" onClick={()=>void refresh()} disabled={loading}><RefreshCw className="mr-1 h-4 w-4"/>Refresh</Button></CardHeader><CardContent className="space-y-2 text-sm">{error&&<p role="alert" className="text-destructive">{error}</p>}{status&&<><p>Combat {status.combatMode} · world {status.worldState} · scheduler {status.schedulerEnabled?'enabled':'disabled'}</p><p>{status.activePresenceCount} active testers · {status.activeEncounterCount} encounters · {status.arenaLiveClaimCount} live claims</p><p>Recording: <b>{status.recordingStatus}</b></p></>} </CardContent></Card>
  <details className="rounded-lg border bg-card p-4"><summary className="cursor-pointer font-semibold">Advanced Diagnostics</summary>{status&&<div className="mt-3 space-y-1 text-sm"><p>Dispatcher: {status.lastDispatcherClassification??'none'} {status.lastDispatcherErrorCode??''}</p><p>Last tick: {status.lastArenaTick??'none'}</p><p>Located testers: {status.locatedTesterCount}</p></div>}</details>
  <Card className="min-w-0 overflow-hidden"><CardHeader><CardTitle>Test Report</CardTitle></CardHeader><CardContent className="min-w-0 space-y-3 text-sm">{!report?<p>No diagnostic run is available.</p>:<><p className="break-words"><b>{report.status}</b> · {shorten(report.runId)}</p><div className="grid min-w-0 grid-cols-2 gap-2">{summaryEntries.map(([k,v])=><div key={k} className="min-w-0 rounded border p-2"><span className="break-words">{k}: </span><b>{v}</b></div>)}</div><ol className="min-w-0 max-h-80 space-y-1 overflow-auto" aria-label="Ordered combat report">{report.batches.flatMap(b=>b.events.map((e,i)=><li key={`${b.seq}-${i}`} className="min-w-0 break-words border-l-2 pl-2">#{b.seq}/tick {b.tick} {arenaReportEventText(e)}</li>))}</ol>{report.hasMore&&<Button variant="outline" size="sm" onClick={()=>void loadReport(report.runId,report.returnedThroughSeq,true)}>Load more</Button>}</>}</CardContent></Card></aside>
 </div></div></div>;
}
