import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe,expect,it } from 'vitest';
const SQL=readFileSync(resolve('supabase/migrations/20260908110000_authoritative_party_lifecycle.sql'),'utf8');
const HOOK=readFileSync(resolve('src/features/party/hooks/useParty.ts'),'utf8');
const ARENA=readFileSync(resolve('src/components/admin/Combat2TestArenaPanel.tsx'),'utf8');
describe('authoritative real-party lifecycle migration',()=>{
 it('uses existing party tables, auth ownership, a globally ordered lock, and durable bound requests',()=>{expect(SQL).toContain('public.parties');expect(SQL).toContain('public.party_members');expect(SQL).toContain('caller uuid:=auth.uid()');expect(SQL).toContain("pg_advisory_xact_lock(hashtextextended('party-lifecycle',0))");for(const field of ['caller_id','actor_character_id','operation','party_id','target_character_id','membership_id'])expect(SQL).toContain(`prior.${field}`);expect(SQL).toContain("'request_id_conflict'");});
 it('covers create/invite/accept/decline/cancel/leave/kick/disband/tank with authored rules',()=>{for(const op of ['create','invite','accept','decline','cancel','leave','kick','disband','set_tank'])expect(SQL).toContain(`_operation='${op}'`);for(const kind of ['already_in_party','already_invited','party_full','leader_must_disband','leader_required','invalid_tank','party_already_disbanded'])expect(SQL).toContain(`'${kind}'`);expect(SQL).toContain('c.current_node_id=actor.current_node_id');expect(SQL).toContain("pm.status='accepted' AND c.hp>0");});
 it('fences active fighters, pending departures, and live claims before accepted identity changes',()=>{expect(SQL).toContain('party_combat_mutation_blocked');expect(SQL).toContain("nf.present AND e.status='active'");expect(SQL).toContain("d.status='pending'");expect(SQL).toContain('e.claim_token IS NOT NULL');expect(SQL).toContain("'combat_active'");});
 it('provides solo-or-one-party preflight and generation-fenced authoritative allies',()=>{expect(SQL).toContain('combat2_party_preflight');expect(SQL).toContain("status='accepted'");expect(SQL).toContain('memberships>1');expect(SQL).toContain("'ambiguous_membership'");expect(SQL).toContain("'party_member',memberships=1");expect(SQL).toContain('party_id_at_entry');expect(SQL).toContain('nf.present AND c.hp>0');});
 it('removes browser writes, scopes Realtime reads, and revokes obsolete RPCs',()=>{expect(SQL).toContain('REVOKE INSERT,UPDATE,DELETE ON public.parties,public.party_members FROM PUBLIC,anon,authenticated');expect(SQL).toContain('Party participants can view');expect(SQL).toContain('REVOKE ALL ON FUNCTION public.accept_party_invite(uuid)');expect(SQL).toContain('REVOKE ALL ON FUNCTION public.set_party_tank(uuid,uuid)');expect(HOOK).not.toMatch(/\.from\(['"](?:parties|party_members)['"]\)/);expect(HOOK).not.toContain("accept_party_invite");expect(HOOK).not.toContain("set_party_tank");});
 it('uses the real party system in the arena and leaves Reset party-neutral',()=>{expect(ARENA).not.toContain('Party-test preparation');expect(ARENA).not.toContain('prepareParty');expect(SQL).not.toContain('combat2_test_party_prepare');expect(SQL).not.toMatch(/combat2_test_reset[\s\S]*DELETE FROM public\.part(?:ies|y_members)/);});
});
