import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
import {definition} from './prepare-progression-001E.mjs';
const {PGlite}=await import(pathToFileURL(resolve(process.argv[2])).href);const read=p=>readFileSync(p,'utf8');let db;
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',owner='cccccccc-cccc-4ccc-8ccc-cccccccccccc',node='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';let seq=1;
const uuid=()=> '00000000-0000-4000-8000-'+String(seq++).padStart(12,'0');
const q=async(s,a=[])=>(await db.query(s,a)).rows;
const call=async(id,amount=1,reason='Support',request=uuid(),who=actor)=>(await q('SELECT admin_respec_award($1,$2,$3,$4,$5) AS r',[who,id,request,amount,reason]))[0].r;
async function target(who=owner,deleted=false){const id=uuid();await q('INSERT INTO characters(id,user_id,current_node_id,level,hp,deleted_at) VALUES($1,$2,$3,1,3,$4)',[id,who,node,deleted?'2026-10-11':null]);await q('INSERT INTO progression_character_state(character_id,opaque_baseline) VALUES($1,progression_snapshot_internal($1))',[id]);return id;}
const tokens=async id=>(await q('SELECT respec_points AS n FROM characters WHERE id=$1',[id]))[0].n;
before(async()=>{db=new PGlite();await db.exec(read('scripts/progression-001C-sql.test.mjs').match(/const fixture=`([\s\S]*?)`;/)[1]);await db.exec(read('scripts/progression-001E-sql.test.mjs').match(/const extra=`([\s\S]*?)`;/)[1]);await db.exec(read('docs/operations/progression-001C-authority.sql'));await db.exec(`INSERT INTO classes(class_key,base_hp,level_bonuses) VALUES('wizard',6,'{}'); ALTER TABLE characters ADD deleted_at timestamptz, ADD rp_total_earned integer NOT NULL DEFAULT 0; CREATE TABLE user_roles(user_id uuid PRIMARY KEY,role text); INSERT INTO user_roles VALUES('${actor}','steward'); INSERT INTO nodes VALUES('${node}',false,'classless'); ALTER TABLE progression_receipt DROP CONSTRAINT progression_receipt_operation_check; ALTER TABLE progression_receipt ADD CONSTRAINT progression_receipt_operation_check CHECK(operation IN('xp','permanent','order','respec','renown'));`);await db.exec(definition(read('drizzle/migrations/0005_progression_001f_canonical_renown_respec_authority.sql'),'progression_validate_fresh_internal').sql);await db.exec(definition(read('scripts/progression-001E-commands.sql'),'progression_refuse_raw_progression_write').sql);await db.exec('CREATE TRIGGER progression_refuse_raw_progression_write BEFORE UPDATE ON characters FOR EACH ROW EXECUTE FUNCTION progression_refuse_raw_progression_write();');await db.exec("CREATE SCHEMA cron; CREATE TABLE cron.job(jobname text); CREATE FUNCTION cron.schedule(text,text,text) RETURNS bigint LANGUAGE plpgsql AS $$BEGIN INSERT INTO cron.job VALUES($1); RETURN 1; END;$$;");await db.exec(read('docs/operations/progression-001G-D4-respec-token-award.sql'));});
after(async()=>{await db.close();});
test('caps, roles, self, target and reason',async()=>{const id=await target();assert.equal((await call(id,2)).reason,'award_cap');assert.equal((await call(id,1,'')).reason,'invalid_request');assert.equal((await call(id,1,' \t\n ')).reason,'invalid_request');assert.equal((await call(id,1,'Support',uuid(),owner)).reason,'unauthorized');assert.equal((await call(await target(actor))).reason,'self_reward_denied');assert.equal((await call(await target(owner,true))).reason,'invalid_target');assert.equal((await call(uuid())).reason,'invalid_target');assert.equal(await tokens(id),0);await q("UPDATE user_roles SET role='overlord'");assert.equal((await call(id,6)).reason,'award_cap');assert.equal((await call(await target(actor),5)).kind,'committed');await q("UPDATE user_roles SET role='steward'");});
test('retry/conflict, canonical version and milestone preservation',async()=>{const id=await target(),request=uuid();const r=await call(id,1,'Reason',request);assert.equal(r.kind,'committed');assert.equal((await call(id,1,'Reason',request)).kind,'replayed');assert.equal((await call(id,1,'Changed',request)).reason,'request_conflict');assert.equal((await call(await target(),1,'Reason',request)).reason,'request_conflict');assert.equal(await tokens(id),1);assert.equal((await q('SELECT count(*)::int AS n FROM progression_respec_milestone'))[0].n,0);assert.equal((await q("SELECT progression_validate_fresh_internal($1,1,'admin_token') AS r",[id]))[0].r.kind,'valid');});
test('failure rolls back token/version/receipt together',async()=>{const id=await target();await db.exec(`CREATE FUNCTION reject_award_log() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'injected'; END;$$; CREATE TRIGGER reject_log BEFORE INSERT ON admin_respec_award_log FOR EACH ROW EXECUTE FUNCTION reject_award_log();`);await assert.rejects(call(id),/injected/);assert.equal(await tokens(id),0);assert.equal((await q('SELECT version FROM progression_character_state WHERE character_id=$1',[id]))[0].version,0);assert.equal((await q('SELECT count(*)::int AS n FROM progression_receipt WHERE character_id=$1',[id]))[0].n,0);await db.exec('DROP TRIGGER reject_log ON admin_respec_award_log;');});
test('private ACL and expired detail does not erase replay',async()=>{for(const role of ['anon','authenticated']){assert.equal((await q("SELECT has_function_privilege($1,'admin_respec_award(uuid,uuid,uuid,integer,text)','EXECUTE') AS ok",[role]))[0].ok,false);}assert.equal((await q("SELECT has_function_privilege('service_role','admin_respec_award_internal(uuid,uuid,uuid,integer,text)','EXECUTE') AS ok"))[0].ok,false);const id=await target(),req=uuid();await call(id,1,'Support',req);await q("UPDATE admin_respec_award_log SET expires_at=now()-interval '1 day' WHERE request_id=$1",[req]);await db.exec('SELECT admin_respec_award_log_expire_internal();');assert.equal((await call(id,1,'Support',req)).kind,'replayed');assert.equal(await tokens(id),1);});

test('custom default grants removed and no resource changes',async()=>{assert.equal((await q("SELECT has_table_privilege('custom_default','admin_respec_award_log','SELECT') AS ok"))[0].ok,false);assert.equal((await q("SELECT has_function_privilege('custom_default','admin_respec_award_internal(uuid,uuid,uuid,integer,text)','EXECUTE') AS ok"))[0].ok,false);const id=await target();const before=(await q('SELECT hp,cp,mp,str,level,xp FROM characters WHERE id=$1',[id]))[0];await call(id);assert.deepEqual((await q('SELECT hp,cp,mp,str,level,xp FROM characters WHERE id=$1',[id]))[0],before);});

test('existing earned milestone preserved exactly',async()=>{const id=await target(),event=uuid();const snap=(await q('SELECT progression_snapshot_internal($1) AS s',[id]))[0].s;await q('UPDATE progression_character_state SET version=1 WHERE character_id=$1',[id]);await q("INSERT INTO progression_receipt VALUES($1,'combat_fixture',$2,'xp','{}',$3)",[id,event,{versionBefore:0,versionAfter:1,after:snap}]);await q("INSERT INTO progression_respec_milestone VALUES($1,10,'combat_fixture',$2)",[id,event]);const before=await q('SELECT * FROM progression_respec_milestone WHERE character_id=$1',[id]);assert.equal((await call(id)).kind,'committed');assert.deepEqual(await q('SELECT * FROM progression_respec_milestone WHERE character_id=$1',[id]),before);});

test('fresh-state exclusions and missing sidecar refuse without award',async()=>{const id=await target();await q('DELETE FROM progression_character_state WHERE character_id=$1',[id]);assert.equal((await call(id)).reason,'missing_provenance');const dead=await target();await q('UPDATE characters SET hp=0 WHERE id=$1',[dead]);assert.equal((await call(dead)).reason,'dead');const stance=await target();await q('INSERT INTO character_stance VALUES($1)',[stance]);assert.equal((await call(stance)).reason,'unsafe_lifecycle');assert.equal(await tokens(stance),0);});
test('service entry callable, browser forbidden, private authority inaccessible',async()=>{const id=await target();await db.exec('SET ROLE service_role');try{assert.equal((await call(id)).kind,'committed');await assert.rejects(q('SELECT admin_respec_award_internal($1,$2,$3,1,$4)',[actor,id,uuid(),'Reason']),/permission denied/);}finally{await db.exec('RESET ROLE');}await db.exec('SET ROLE authenticated');try{await assert.rejects(call(id),/permission denied/);}finally{await db.exec('RESET ROLE');}});

test('installation refuses receipt constraint drift and rolls back schema',async()=>{await db.exec('BEGIN');try{await db.exec(`DROP INDEX progression_admin_token_request; DROP FUNCTION admin_respec_award(uuid,uuid,uuid,integer,text); DROP FUNCTION admin_respec_award_internal(uuid,uuid,uuid,integer,text); DROP FUNCTION admin_respec_award_log_expire_internal(); DROP TABLE admin_respec_award_log; ALTER TABLE progression_receipt DROP CONSTRAINT progression_receipt_operation_check; ALTER TABLE progression_receipt ADD CONSTRAINT progression_receipt_operation_check CHECK(operation IN('xp','permanent','order','respec','renown','admin_token'));`);await assert.rejects(db.exec(read('docs/operations/progression-001G-D4-respec-token-award.sql')),/constraint drift/);}finally{await db.exec('ROLLBACK');}});
