/** Pure local HTTP boundary probes; no credentials, hosted calls or gameplay writes. */
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
const {build}=createRequire(import.meta.resolve('vite'))('esbuild');
const compiled=await build({entryPoints:['supabase/functions/_shared/progression-command.ts'],bundle:true,write:false,format:'esm',platform:'node'});
const {createProgressionCommandHandler}=await import('data:text/javascript;base64,'+Buffer.from(compiled.outputFiles[0].text).toString('base64'));
function fixture(actor=null,result={kind:'refused',reason:'commands_paused'}){let verification=0,commands=0;return {handler:createProgressionCommandHandler({verifyActor:async()=>{verification++;return actor;},command:async()=>{commands++;return result;}}),counts:()=>({verification,commands})};}
test('OPTIONS 200 empty body/CORS, before auth or RPC',async()=>{const f=fixture(),r=await f.handler(new Request('https://local.invalid',{method:'OPTIONS'}));assert.equal(r.status,200);assert.equal(await r.text(),'');assert.equal(r.headers.get('Access-Control-Allow-Methods'),'POST, OPTIONS');assert.deepEqual(f.counts(),{verification:0,commands:0});});
test('GET 405 exact envelope before auth or RPC',async()=>{const f=fixture(),r=await f.handler(new Request('https://local.invalid'));assert.equal(r.status,405);assert.deepEqual(await r.json(),{kind:'refused',reason:'method_not_allowed'});assert.deepEqual(f.counts(),{verification:0,commands:0});});
test('POST without bearer 401 exact envelope before auth or RPC',async()=>{const f=fixture(),r=await f.handler(new Request('https://local.invalid',{method:'POST',body:'{}'}));assert.equal(r.status,401);assert.deepEqual(await r.json(),{kind:'refused',reason:'unauthorized'});assert.deepEqual(f.counts(),{verification:0,commands:0});});
test('POST invalid/no-user subject 401 never reaches RPC',async()=>{const f=fixture(),r=await f.handler(new Request('https://local.invalid',{method:'POST',headers:{Authorization:'Bearer invalid-fixture'},body:'{}'}));assert.equal(r.status,401);assert.deepEqual(await r.json(),{kind:'refused',reason:'unauthorized'});assert.deepEqual(f.counts(),{verification:1,commands:0});});
test('optional safely authenticated malformed/schema probes 400 before command',async()=>{for(const body of ['{','{}']){const f=fixture('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),r=await f.handler(new Request('https://local.invalid',{method:'POST',headers:{Authorization:'Bearer fixture'},body}));assert.equal(r.status,400);assert.deepEqual(await r.json(),{kind:'refused',reason:'invalid_request'});assert.equal(f.counts().commands,0);}});
test('optional paused envelope is returned unchanged; actual SQL pause/no-mutation proved separately',async()=>{const f=fixture('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),r=await f.handler(new Request('https://local.invalid',{method:'POST',headers:{Authorization:'Bearer fixture'},body:JSON.stringify({characterId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',requestId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',expectedVersion:0,operation:'respec'})}));assert.equal(r.status,200);assert.deepEqual(await r.json(),{kind:'refused',reason:'commands_paused'});assert.equal(f.counts().commands,1);assert.match(readFileSync('supabase/config.toml','utf8'),/\[functions\.progression-command\]\s*verify_jwt = false/);});
