// Disposable local data only, seeded from the exact approved CSV; no hosted access.
import { test,before,after } from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';
if(!process.argv[2])throw Error('Supply local PGlite module path');
const {PGlite}=await import(pathToFileURL(resolve(process.argv[2])).href);
const cleanup=readFileSync('docs/operations/progression-001G-C2-orphan-cleanup-template.sql','utf8');
const csv=readFileSync('docs/operations/progression-001G-C2-orphan-materials-snapshot.csv','utf8').trim().split(/\r?\n/).slice(1).map(r=>r.split(','));
const values=csv.map(r=>`('${r[0]}','${r[1]}',${r[2]},'${r[3]}')`).join(',');
const subject=csv[0][0],live='11111111-1111-4111-8111-111111111111';let db;
const q=async(s,p=[])=>(await db.query(s,p)).rows;
before(async()=>{db=new PGlite();await db.exec(`CREATE TABLE characters(id uuid PRIMARY KEY);
 CREATE TABLE character_materials(character_id uuid,material_key text,count integer,updated_at timestamptz,PRIMARY KEY(character_id,material_key));
 CREATE TABLE character_inventory(character_id uuid);CREATE TABLE progression_character_state(character_id uuid);
 CREATE TABLE character_creation_origin(character_id uuid);CREATE TABLE character_creation_log(result_character_id uuid);CREATE TABLE character_lifecycle_receipt(character_id uuid);
 INSERT INTO characters VALUES('${live}');INSERT INTO character_materials VALUES('${live}','salvage',400,'2020-01-01');
 INSERT INTO character_materials VALUES ${values};
 ALTER TABLE character_materials ADD CONSTRAINT character_materials_character_id_c2_fkey FOREIGN KEY(character_id) REFERENCES characters(id) ON UPDATE RESTRICT ON DELETE CASCADE NOT VALID;`);});
after(async()=>await db?.close());
async function tx(fn){await db.exec('BEGIN');try{await fn();}finally{await db.exec('ROLLBACK');}}
async function refused(s,pattern=/snapshot drift|live character|approved203|FK/){await db.exec('SAVEPOINT refusal');try{await assert.rejects(()=>db.exec(s),pattern);}finally{await db.exec('ROLLBACK TO SAVEPOINT refusal');}}
test('approved CSV matches exact SQL rows and aggregate counts',()=>tx(async()=>{assert.equal(csv.length,203);assert.equal(new Set(csv.map(r=>r[0])).size,29);assert.equal(csv.reduce((n,r)=>n+Number(r[2]),0),1341);await db.exec(cleanup);assert.deepEqual(await q('SELECT count FROM character_materials'),[{count:400}]);}));
test('cleanup is atomic and leaves FK validation ready; rollback restores snapshot and unvalidated FK',async()=>{await tx(async()=>{await db.exec(cleanup);await db.exec('ALTER TABLE character_materials VALIDATE CONSTRAINT character_materials_character_id_c2_fkey');assert.equal((await q("SELECT convalidated FROM pg_constraint WHERE conname='character_materials_character_id_c2_fkey'"))[0].convalidated,true);assert.equal((await q('SELECT count(*)::int n FROM characters'))[0].n,1);});assert.equal((await q('SELECT count(*)::int n FROM character_materials'))[0].n,204);assert.equal((await q("SELECT convalidated FROM pg_constraint WHERE conname='character_materials_character_id_c2_fkey'"))[0].convalidated,false);});
test('missing/changed key, amount, microsecond timestamp or newly existing parent refuse all-or-nothing',()=>tx(async()=>{for(const sql of ["UPDATE character_materials SET count=count+1 WHERE character_id=$1","UPDATE character_materials SET updated_at=updated_at+interval '1 microsecond' WHERE character_id=$1","UPDATE character_materials SET material_key='changed' WHERE character_id=$1 AND material_key='amethyst'","DELETE FROM character_materials WHERE character_id=$1","INSERT INTO characters VALUES($1)"]){await db.exec('SAVEPOINT change');await db.exec('ALTER TABLE character_materials DISABLE TRIGGER ALL');await q(sql,[subject]);await db.exec('ALTER TABLE character_materials ENABLE TRIGGER ALL');await refused(cleanup);await db.exec('ROLLBACK TO SAVEPOINT change');}}));
test('additional orphan rejects even when every expected row is unchanged',()=>tx(async()=>{await db.exec('ALTER TABLE character_materials DISABLE TRIGGER ALL');await q("INSERT INTO character_materials VALUES('22222222-2222-4222-8222-222222222222','salvage',1,now())");await db.exec('ALTER TABLE character_materials ENABLE TRIGGER ALL');await refused(cleanup,/additional orphan/);}));
test('UTC instant comparison works under non-UTC session timezone and timestamp display settings',()=>tx(async()=>{await db.exec("SET LOCAL TimeZone='Pacific/Auckland';SET LOCAL DateStyle='SQL, DMY';");await db.exec(cleanup);assert.deepEqual(await q('SELECT count FROM character_materials'),[{count:400}]);}));
test('surviving inventory, progression, provenance, replay or lifecycle evidence blocks cleanup',()=>tx(async()=>{for(const table of ['character_inventory','progression_character_state','character_creation_origin','character_creation_log','character_lifecycle_receipt']){await db.exec('SAVEPOINT evidence');await q(`INSERT INTO ${table} VALUES($1)`,[subject]);await refused(cleanup,/recovery evidence/);await db.exec('ROLLBACK TO SAVEPOINT evidence');}}));
test('incoming FK or user trigger rejects unreviewed side effects',()=>tx(async()=>{await db.exec('SAVEPOINT dep');await db.exec('CREATE TABLE unexpected_reference(character_id uuid,material_key text,FOREIGN KEY(character_id,material_key) REFERENCES character_materials(character_id,material_key) ON DELETE CASCADE)');await refused(cleanup,/unexpected materials/);await db.exec('ROLLBACK TO SAVEPOINT dep');await db.exec('CREATE FUNCTION unexpected_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN OLD;END $$;CREATE TRIGGER unexpected_delete BEFORE DELETE ON character_materials FOR EACH ROW EXECUTE FUNCTION unexpected_delete()');await refused(cleanup,/unexpected materials/);}));
test('late post-delete FK-definition assertion failure rolls back all deleted rows',()=>tx(async()=>{await db.exec('ALTER TABLE character_materials RENAME CONSTRAINT character_materials_character_id_c2_fkey TO unexpected_fk');await refused(cleanup,/FK definition drift/);assert.equal((await q('SELECT count(*)::int n FROM character_materials'))[0].n,204);}));
