/** Audit-only characterization: exact pre-E browser callback and frozen legacy Renown SQL. */
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createRequire} from 'node:module';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {read,definition} from './prepare-progression-001E.mjs';
const {build,transform}=createRequire(import.meta.resolve('vite'))('esbuild');
const historical=execFileSync('git',['show','fc370869:src/features/character/hooks/useStatAllocation.ts'],{encoding:'utf8'});
const body=historical.match(/const handleFullRespec = useCallback\(async \(\) => \{([\s\S]*?)\}, \[character/)[1];
const compiled=await transform(`export async function run(character:any,updateCharacter:any,syncResources:any,addLogEvent:any,buildProgressionEvent:any,calculateStats:any,CLASS_LEVEL_BONUSES:any,onResourcesSynced:any){${body}}`,{loader:'ts',format:'esm'});
const {run}=await import('data:text/javascript;base64,'+Buffer.from(compiled.code).toString('base64'));
const dataBuild=await build({stdin:{contents:"export {calculateStats,CLASS_LEVEL_BONUSES} from './src/lib/game-data';",resolveDir:process.cwd()},bundle:true,write:false,platform:'node',format:'esm'});
const formulas=await import('data:text/javascript;base64,'+Buffer.from(dataBuild.outputFiles[0].text).toString('base64'));
async function oldRespec(fields={},syncFails=false){const base=formulas.calculateStats('human','classless');const c={id:'fixture',race:'human',class:'wizard',level:3,respec_points:1,unspent_stat_points:0,bhp_trained:{},...base,...fields};let write=null;const calls=[];await run(c,async v=>{write=v;calls.push('write');},async()=>{calls.push('sync');if(syncFails)throw Error('sync failed');},()=>calls.push('log'),x=>x,formulas.calculateStats,formulas.CLASS_LEVEL_BONUSES,null).catch(e=>calls.push(e.message));return {c,write,calls};}
test('historical browser respec subtracts current-class reconstruction with destination-level off-by-one',async()=>{const base=formulas.calculateStats('human','classless');const bonus=formulas.CLASS_LEVEL_BONUSES.wizard.int;assert.ok(bonus>0);const r=await oldRespec({int:base.int+bonus});assert.equal(r.write.int,base.int);assert.equal(r.write.unspent_stat_points,bonus);});
test('historical Renown/high opaque stats become refundable and ranks survive contradictory stat reset',async()=>{const b=formulas.calculateStats('human','classless');const r=await oldRespec({level:1,str:b.str+7,bhp_trained:{str:2}});assert.equal(r.write.str,b.str);assert.equal(r.write.unspent_stat_points,7);assert.equal(r.c.bhp_trained.str,2);assert.equal(r.write.bhp_trained,undefined);});
test('historical empty respec spends token; synchronization is a separate failure after character write',async()=>{const r=await oldRespec({level:1},true);assert.equal(r.write.respec_points,0);assert.equal(r.write.unspent_stat_points,0);assert.deepEqual(r.calls,['write','sync','sync failed']);});
let db;before(async()=>{if(!process.argv[2])throw Error('Supply pinned local PGlite module');const {PGlite}=await import(pathToFileURL(resolve(process.argv[2])).href);db=new PGlite();await db.exec(`CREATE TABLE characters(id uuid PRIMARY KEY,level int,bhp int,bhp_trained jsonb,str int,dex int,con int,int int,wis int,cha int,max_hp int,max_cp int,max_mp int);
 CREATE TABLE progression_character_state(character_id uuid,version bigint,str_invested int);
 CREATE FUNCTION owns_character(uuid) RETURNS boolean LANGUAGE sql AS $$ SELECT true $$;
 CREATE FUNCTION sync_character_resources(uuid) RETURNS void LANGUAGE sql AS $$ SELECT $$;
 INSERT INTO characters VALUES('11111111-1111-4111-8111-111111111111',30,1000,'{"str":2}',10,10,10,10,10,10,20,30,100);
 INSERT INTO progression_character_state VALUES('11111111-1111-4111-8111-111111111111',7,3);`+definition(read('supabase/migrations/20260731072756_3e051877-cae6-4323-9e35-a5b19fb63857.sql'),'train_renown_stat').sql);});after(async()=>await db?.close());
test('exact frozen Renown uses selected-stat rank; spends RP on a real failed roll; no provenance mutation',async()=>{
 const id='11111111-1111-4111-8111-111111111111';await db.exec('BEGIN');try{await db.exec('SELECT setseed(0.42)');const a=(await db.query('SELECT train_renown_stat($1,$2) r',[id,'str'])).rows[0].r;assert.equal(a.cost,30);assert.equal(a.chance,75);const b=(await db.query('SELECT train_renown_stat($1,$2) r',[id,'dex'])).rows[0].r;assert.equal(b.cost,10);assert.equal(b.chance,95);assert.equal(b.bhp,960);assert.deepEqual((await db.query('SELECT version,str_invested FROM progression_character_state')).rows,[{version:7,str_invested:3}]);
 await db.exec("UPDATE characters SET bhp_trained='{\"str\":9}',bhp=1000;SELECT setseed(0.42)");const c=(await db.query('SELECT train_renown_stat($1,$2) r',[id,'str'])).rows[0].r;assert.equal(c.chance,5);assert.equal(c.success,false);assert.equal(c.bhp,900);assert.equal(c.rank,9);
 }finally{await db.exec('ROLLBACK');}
});
test('current runtime contains explicit F refusal, and E gate intentionally omits currency/rank freshness',()=>{assert.match(read('src/features/character/hooks/useStatAllocation.ts'),/Respec is unavailable/);assert.match(read('src/features/character/components/TrainerPanel.tsx'),/respecAvailable = false/);const s=read('scripts/progression-001E-commands.sql');assert.match(s,/refundableInvestmentAfter/);assert.doesNotMatch(s,/latest\.receipt[^\n]*(trainedRanks|renownBalance)/);});
