import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const valueAfter=flag=>{const index=process.argv.indexOf(flag);return index>=0?process.argv[index+1]:null;};
const source=resolve(valueAfter('--state')??'docs/operations/project-state.json');
const output=resolve(valueAfter('--output')??'docs/operations/project-state.md');
const allowed=new Set(['authored','committed','pushed','installed','deployed','ready_for_manual_publish','manually_published','blocked','unknown']);
const sha=/^[0-9a-f]{40}$/;
const forbiddenKey=/(secret|token|password|credential|authorization|cookie|email)/i;

function entries(state){return [state.repository,state.generated_supabase_types,state.frontend_publication,state.next_approved_task,
  ...state.database_migrations,...state.edge_function_deployments,...state.combat2_operational_work,...state.known_blockers,...state.volatile_runtime_observations];}
function validate(state){
  const errors=[];
  if(state.schema_version!==1)errors.push('schema_version must be 1');
  if(!sha.test(state.based_on_source_sha??''))errors.push('based_on_source_sha must be a 40-character lowercase SHA');
  if(JSON.stringify([...allowed])!==JSON.stringify(state.status_vocabulary))errors.push('status_vocabulary does not match the documented vocabulary');
  const ids=new Set();
  for(const [index,item] of entries(state).entries()){
    if(!item||!allowed.has(item.status))errors.push(`entry ${index} has invalid status`);
    for(const field of ['evidence_type','evidence','reporting_actor','directly_verified'])if(item?.[field]===undefined)errors.push(`entry ${index} lacks ${field}`);
    if(item?.sha!==null&&item?.sha!==undefined&&!sha.test(item.sha))errors.push(`entry ${index} has invalid SHA`);
    if(item?.identity){if(ids.has(item.identity))errors.push(`duplicate identity ${item.identity}`);ids.add(item.identity);}
    if(item?.status==='installed'&&!['cloud_inspection','operator_reported'].includes(item.evidence_type))errors.push(`${item.identity} installed without installation evidence`);
    if(item?.status==='deployed'&&!['cloud_inspection','operator_reported'].includes(item.evidence_type))errors.push(`${item.identity} deployed without deployment evidence`);
  }
  if(state.frontend_publication.status==='manually_published'&&state.frontend_publication.evidence_type!=='operator_reported')errors.push('manually_published requires operator_reported evidence');
  const walk=(value,path='root')=>{if(Array.isArray(value))value.forEach((v,i)=>walk(v,`${path}[${i}]`));else if(value&&typeof value==='object')for(const [key,v]of Object.entries(value)){if(forbiddenKey.test(key))errors.push(`credential-shaped field is forbidden: ${path}.${key}`);walk(v,`${path}.${key}`);}};
  walk(state); return errors;
}
const line=item=>`| ${item.identity??item.artifact??'state'} | ${item.status} | ${item.sha??'—'} | ${item.evidence_type} | ${item.directly_verified?'direct':'reported/unknown'} | ${item.evidence.replaceAll('|','\\|')} |`;
function render(s){return `<!-- Generated by scripts/project-state.mjs. Edit project-state.json, not this file. -->
# WoV project state

Based on source SHA: \`${s.based_on_source_sha}\`
Last recorded update: ${s.updated_at}

GitHub \`origin/main\` is authoritative for source. Repository presence does not prove installation, deployment, or frontend publication. A descendant SHA is valid when ancestry is verified. Only Mik manually publishes the frontend.

| Area/artifact | Status | SHA | Evidence | Verification | Note |
|---|---|---|---|---|---|
${entries(s).map(line).join('\n')}

## Next approved task

${s.next_approved_task.artifact}

## Required validation before work

Fetch \`origin/main\`, verify ancestry from the recorded baseline, run \`npm run project-state:check\`, and obtain fresh authorized evidence before changing any Cloud or volatile runtime status. Unknown facts remain unknown.
`;}
const state=JSON.parse(await readFile(source,'utf8'));const errors=validate(state);if(errors.length){console.error(errors.join('\n'));process.exit(1);}const markdown=render(state);
if(process.argv.includes('--write')){await writeFile(output,markdown,'utf8');console.log('project-state.md generated');}
else{const current=await readFile(output,'utf8').catch(()=>null);if(current!==markdown){console.error('project-state.md is not synchronized; run npm run project-state:generate');process.exit(1);}console.log('project state valid and synchronized');}
