-- ONE coordinated Drizzle transaction: approved one-time reset, then corrected C2 cutover B.
-- NOT INSTALLED. Requires separately installed inactive A, recovery checkpoint and explicit execution approval.
-- Generated by scripts/prepare-c2-reset-cutover.mjs. Never install reset or components independently.

-- Component: progression-001G-C2-character-reset.sql; SHA-256 02da4e8aa9d884cf665456a3c32477b44a57e56705686f50c7b97151fd5f7122
-- One-time owner-approved disposable test-character reset. NOT INSTALLED/EXECUTED.
-- ONLY the coordinated reset + existing B artifact may be installed, in ONE Drizzle transaction.
-- Separate unchanged inactive support A must already be installed. Recovery checkpoint +
-- fresh metadata review + explicit destructive/cutover approval are external execution gates.
-- No CASCADE reset, trigger disable, constraint drop, account deletion or history rewrite.
SET LOCAL lock_timeout='5s';
SET LOCAL statement_timeout='120s';
CREATE TEMP TABLE c2_reset_allowlist(name text PRIMARY KEY, relation oid, mode text NOT NULL,
 done boolean NOT NULL DEFAULT false) ON COMMIT DROP;
INSERT INTO c2_reset_allowlist(name,mode) VALUES
('active_effects','all'),
('character_ability_loadout','all'),
('character_class_bonds','all'),
('character_creation_log','all'),
('character_creation_origin','all'),
('character_guide_reads','all'),
('character_inventory','all'),
('character_inventory_action_request','all'),
('character_lifecycle_receipt','all'),
('character_materials','all'),
('character_npc_gifts','all'),
('character_special_travel_request','all'),
('character_stance','all'),
('character_stance_request','all'),
('character_visited_nodes','all'),
('character_waymark','all'),
('characters','all'),
('combat2_departure_request','all'),
('combat2_diagnostic_server_event','all'),
('combat2_diagnostic_session','all'),
('combat2_party_departure_member','all'),
('combat2_party_departure_request','all'),
('combat2_player_presence','all'),
('combat2_respawn_request','all'),
('combat2_test_arena_access','all'),
('combat2_test_arena_stance_snapshot','all'),
('combat2_test_arena_stance_snapshot_header','all'),
('combat2_test_presence','all'),
('combat2_tick_notification','all'),
('combat_actions','all'),
('combat_audit_log','all'),
('combat_sessions','all'),
('combat_soak_access','all'),
('combat_soak_scopes','all'),
('effects_catchup_dispatch','all'),
('effects_catchup_log','all'),
('encounter_access_grants','all'),
('encounter_cast_events','all'),
('encounter_contributions','all'),
('encounter_creatures','all'),
('encounter_death_loot','all'),
('encounter_engagements','all'),
('encounter_kill_awards','all'),
('encounter_participants','all'),
('encounter_tick_batches','all'),
('encounters','all'),
('hidden_path_search_request','all'),
('marketplace_listings','all'),
('node_arrival_group','all'),
('node_boss_ability_cooldown','all'),
('node_creature','all'),
('node_death_loot','all'),
('node_effect','all'),
('node_encounter','all'),
('node_fighter','all'),
('node_ground_loot','all'),
('node_intent','all'),
('node_participation','all'),
('node_pending_event','all'),
('node_reward_claim','all'),
('node_tick_batch','all'),
('node_tick_log','all'),
('parties','all'),
('party_combat_log','all'),
('party_members','all'),
('party_operation_request','all'),
('progression_character_state','all'),
('progression_class_growth_milestone','all'),
('progression_receipt','all'),
('progression_respec_milestone','all'),
('summon_requests','all'),
('unique_item_instance','all'),
('combat2_test_run','recording'),('combat2_test_run_batch','recording'),
('combat2_test_run_event','recording'),('issue_reports','unlink');
UPDATE c2_reset_allowlist SET relation=to_regclass('public.'||quote_ident(name));
CREATE TEMP TABLE c2_reset_preserved(name text NOT NULL, row_value jsonb NOT NULL) ON COMMIT DROP;
CREATE TEMP TABLE c2_reset_trigger_body(name text PRIMARY KEY, body_md5 text NOT NULL) ON COMMIT DROP;
INSERT INTO c2_reset_trigger_body VALUES
('unique_holder_before_delete','b526d9a05105dbb635cc8198ef966777'),
('unique_holder_finalize_delete','a53c5505f41b99178789ab88831fa56d'),
('combat2_refuse_invalid_stance_equipment_change','5cb5bdf9f5adb09288b9f7a229d7fc80');
DO $reset$
DECLARE target_record record; next_table text; n bigint; problem text;
 preserved_names text[]:=ARRAY['items','vendor_inventory','nodes','node_connections','worlds','regions','areas',
  'creatures','node_creature_spawns','boss_abilities','node_boss_config','families','family_members','family_requests',
  'user_roles','combat_config','combat2_respawn_config','combat2_canary_node','combat2_dispatch_schedule_state',
  'combat2_test_arena','combat2_test_arena_node','combat2_test_arena_creature','combat2_test_arena_request',
  'character_resource_settlement_state','progression_command_control','world_slumber_log'];
BEGIN
 IF current_user<>'postgres' THEN RAISE EXCEPTION 'C2 reset requires postgres installer'; END IF;
 IF to_regclass('public.characters') IS NULL OR to_regclass('public.character_materials') IS NULL
  OR to_regclass('public.character_creation_origin') IS NULL OR to_regclass('public.progression_character_state') IS NULL
  OR to_regclass('auth.users') IS NULL THEN RAISE EXCEPTION 'C2 reset missing core dependency'; END IF;
 -- Ordinary installed relations only; missing legacy source candidates are recorded by preflight.
 SELECT a.name INTO problem FROM c2_reset_allowlist a JOIN pg_class c ON c.oid=a.relation
 WHERE c.relkind<>'r' OR c.relispartition OR EXISTS(SELECT 1 FROM pg_inherits i WHERE i.inhparent=c.oid OR i.inhrelid=c.oid) LIMIT 1;
 IF problem IS NOT NULL THEN RAISE EXCEPTION 'C2 reset unsupported relation: %',problem; END IF;
 -- Deterministic maintenance locks retained through cutover/commit, no writer window.
 FOR target_record IN SELECT name FROM c2_reset_allowlist WHERE relation IS NOT NULL ORDER BY name LOOP
  EXECUTE format('LOCK TABLE public.%I IN ACCESS EXCLUSIVE MODE',target_record.name);
  IF row_security_active(('public.'||quote_ident(target_record.name))::regclass) THEN
   RAISE EXCEPTION 'C2 reset incomplete visibility: %',target_record.name; END IF;
 END LOOP;
 -- Any edge from outside the allowlist into a deleted table is a preservation blocker,
 -- regardless of delete action. Archival rows cannot be rewritten by SET NULL either.
 SELECT k.conname||' on '||k.conrelid::regclass INTO problem FROM pg_constraint k
 JOIN c2_reset_allowlist parent ON parent.relation=k.confrelid
 LEFT JOIN c2_reset_allowlist child ON child.relation=k.conrelid
 WHERE k.contype='f' AND (child.relation IS NULL OR child.mode<>'all' AND parent.mode='all')
 AND NOT coalesce((child.name='issue_reports' AND parent.name='characters'
  AND k.conkey=ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid=k.conrelid AND attname='character_id')]::smallint[]),false)
 LIMIT 1;
 IF problem IS NOT NULL THEN RAISE EXCEPTION 'C2 reset preserved incoming FK: %',problem; END IF;
 -- Catch a new sidecar omitted from the reviewed inventory even if it has no FK.
 SELECT c.oid::regclass::text INTO problem FROM pg_class c JOIN pg_namespace s ON s.oid=c.relnamespace
 JOIN pg_attribute p ON p.attrelid=c.oid AND p.attnum>0 AND NOT p.attisdropped
 WHERE s.nspname='public' AND c.relkind IN ('r','p') AND p.attname IN
  ('character_id','source_character_id','target_character_id','actor_character_id','leader_character_id',
   'seller_character_id','buyer_character_id','summoner_character_id','result_character_id')
 AND NOT EXISTS(SELECT 1 FROM c2_reset_allowlist a WHERE a.relation=c.oid)
 LIMIT 1;
 IF problem IS NOT NULL THEN RAISE EXCEPTION 'C2 reset unlisted character dependency: %',problem; END IF;
 -- Preserve ordinary holder DELETE triggers. Unexpected or drifted enabled user triggers
 -- (including an already-attached lifecycle fence) refuse, never bypass.
 SELECT t.tgname||' on '||t.tgrelid::regclass INTO problem FROM pg_trigger t
 JOIN c2_reset_allowlist a ON a.relation=t.tgrelid JOIN pg_proc p ON p.oid=t.tgfoid
 LEFT JOIN c2_reset_trigger_body b ON b.name=p.proname
 WHERE NOT t.tgisinternal AND t.tgenabled<>'D'
 AND ((t.tgtype::integer & 8)<>0 OR (a.mode='unlink' OR a.name='unique_item_instance') AND (t.tgtype::integer & 16)<>0)
 AND NOT coalesce((a.mode='all' AND t.tgenabled='O' AND (t.tgtype::integer & 1)<>0
  AND p.pronamespace='public'::regnamespace AND p.proowner='postgres'::regrole AND p.prosecdef
  AND p.proconfig=ARRAY['search_path=public, pg_temp']::text[]
  AND md5(replace(p.prosrc,chr(13)||chr(10),chr(10)))=b.body_md5 AND
  ((p.proname IN ('unique_holder_before_delete','unique_holder_finalize_delete')
    AND a.name IN ('character_inventory','node_ground_loot','marketplace_listings'))
   OR (p.proname='combat2_refuse_invalid_stance_equipment_change' AND a.name='character_inventory'))),false)
 LIMIT 1;
 IF problem IS NOT NULL THEN RAISE EXCEPTION 'C2 reset unreviewed DELETE/update trigger: %',problem; END IF;
 IF current_setting('session_replication_role')<>'origin' THEN RAISE EXCEPTION 'C2 reset requires enabled ordinary triggers'; END IF;
 IF to_regclass('public.unique_item_instance') IS NOT NULL THEN
  IF EXISTS(SELECT 1 FROM public.unique_item_instance WHERE location_kind IS NULL
    OR location_kind NOT IN ('inventory','ground','marketplace','transit')) THEN
   RAISE EXCEPTION 'C2 reset unknown persistent unique location'; END IF;
 END IF;
 -- Account/auth identity preservation reads identifiers ONLY, never credential columns.
 LOCK TABLE auth.users IN SHARE MODE;
 INSERT INTO c2_reset_preserved SELECT 'auth.users',jsonb_build_object('id',id) FROM auth.users;
 IF to_regclass('public.profiles') IS NOT NULL THEN
  EXECUTE 'LOCK TABLE public.profiles IN SHARE MODE';
  EXECUTE 'INSERT INTO c2_reset_preserved SELECT ''profiles'',jsonb_build_object(''id'',id) FROM public.profiles';
 END IF;
 -- No access, hash or snapshot of progression_renown_key or auth secret material.
 FOREACH next_table IN ARRAY preserved_names LOOP
  IF to_regclass('public.'||quote_ident(next_table)) IS NOT NULL THEN
   EXECUTE format('LOCK TABLE public.%I IN SHARE MODE',next_table);
   EXECUTE format('INSERT INTO c2_reset_preserved SELECT %L,to_jsonb(x) FROM public.%I x',next_table,next_table);
  END IF;
 END LOOP;
 IF to_regclass('public.combat2_test_run') IS NOT NULL THEN
  IF EXISTS(SELECT 1 FROM public.combat2_test_run WHERE status IS NULL OR status NOT IN ('recording','completed')) THEN
   RAISE EXCEPTION 'C2 reset unknown Arena report status'; END IF;
  INSERT INTO c2_reset_preserved SELECT 'combat2_test_run',to_jsonb(x) FROM public.combat2_test_run x WHERE status='completed';
  INSERT INTO c2_reset_preserved SELECT 'combat2_test_run_batch',to_jsonb(x) FROM public.combat2_test_run_batch x
   WHERE EXISTS(SELECT 1 FROM public.combat2_test_run r WHERE r.id=x.run_id AND r.status='completed');
  INSERT INTO c2_reset_preserved SELECT 'combat2_test_run_event',to_jsonb(x) FROM public.combat2_test_run_event x
   WHERE EXISTS(SELECT 1 FROM public.combat2_test_run r WHERE r.id=x.run_id AND r.status='completed');
  IF EXISTS(SELECT 1 FROM public.combat2_test_run_batch x WHERE NOT EXISTS(SELECT 1 FROM public.combat2_test_run r WHERE r.id=x.run_id))
   OR EXISTS(SELECT 1 FROM public.combat2_test_run_event x WHERE NOT EXISTS(SELECT 1 FROM public.combat2_test_run r WHERE r.id=x.run_id)) THEN
   RAISE EXCEPTION 'C2 reset detached Arena archive'; END IF;
  DELETE FROM public.combat2_test_run_event e USING public.combat2_test_run r WHERE e.run_id=r.id AND r.status='recording';
  DELETE FROM public.combat2_test_run_batch b USING public.combat2_test_run r WHERE b.run_id=r.id AND r.status='recording';
  DELETE FROM public.combat2_test_run WHERE status='recording';
 END IF;
 IF to_regclass('public.issue_reports') IS NOT NULL THEN
  INSERT INTO c2_reset_preserved SELECT 'issue_reports',to_jsonb(x)-'character_id' FROM public.issue_reports x;
  UPDATE public.issue_reports SET character_id=NULL WHERE character_id IS NOT NULL;
 END IF;
 -- Leaves before parents according to actual FKs, but only allowlisted tables.
 -- Clear stances before shield inventory; registry after ordinary holder deletion.
 UPDATE c2_reset_allowlist SET done=true WHERE relation IS NULL OR mode<>'all';
 WHILE EXISTS(SELECT 1 FROM c2_reset_allowlist WHERE NOT done) LOOP
  SELECT a.name INTO next_table FROM c2_reset_allowlist a WHERE NOT a.done
   AND NOT EXISTS(SELECT 1 FROM pg_constraint k JOIN c2_reset_allowlist child ON child.relation=k.conrelid
    WHERE k.contype='f' AND k.confrelid=a.relation AND k.conrelid<>k.confrelid AND NOT child.done)
   AND NOT (a.name='character_inventory' AND EXISTS(SELECT 1 FROM c2_reset_allowlist WHERE name='character_stance' AND NOT done))
   AND NOT (a.name='unique_item_instance' AND EXISTS(SELECT 1 FROM c2_reset_allowlist
      WHERE name IN ('character_inventory','node_ground_loot','marketplace_listings') AND NOT done))
   ORDER BY a.name LIMIT 1;
  IF next_table IS NULL THEN RAISE EXCEPTION 'C2 reset cyclic or unreviewed dependency order'; END IF;
  EXECUTE format('DELETE FROM public.%I',next_table);
  UPDATE c2_reset_allowlist SET done=true WHERE name=next_table;
 END LOOP;
 -- Flush FK/holder deferred finalization while assertions and cutover can still roll back.
 SET CONSTRAINTS ALL IMMEDIATE;
 FOR target_record IN SELECT name FROM c2_reset_allowlist WHERE relation IS NOT NULL AND mode='all' LOOP
  EXECUTE format('SELECT count(*) FROM public.%I',target_record.name) INTO n;
  IF n<>0 THEN RAISE EXCEPTION 'C2 reset nonempty target: %',target_record.name; END IF;
 END LOOP;
 CREATE TEMP TABLE c2_reset_after (LIKE c2_reset_preserved) ON COMMIT DROP;
 INSERT INTO c2_reset_after SELECT 'auth.users',jsonb_build_object('id',id) FROM auth.users;
 IF to_regclass('public.profiles') IS NOT NULL THEN
  EXECUTE 'INSERT INTO c2_reset_after SELECT ''profiles'',jsonb_build_object(''id'',id) FROM public.profiles'; END IF;
 FOREACH next_table IN ARRAY preserved_names LOOP
  IF to_regclass('public.'||quote_ident(next_table)) IS NOT NULL THEN
   EXECUTE format('INSERT INTO c2_reset_after SELECT %L,to_jsonb(x) FROM public.%I x',next_table,next_table); END IF;
 END LOOP;
 IF to_regclass('public.combat2_test_run') IS NOT NULL THEN
  INSERT INTO c2_reset_after SELECT 'combat2_test_run',to_jsonb(x) FROM public.combat2_test_run x;
  INSERT INTO c2_reset_after SELECT 'combat2_test_run_batch',to_jsonb(x) FROM public.combat2_test_run_batch x;
  INSERT INTO c2_reset_after SELECT 'combat2_test_run_event',to_jsonb(x) FROM public.combat2_test_run_event x;
 END IF;
 IF to_regclass('public.issue_reports') IS NOT NULL THEN
  INSERT INTO c2_reset_after SELECT 'issue_reports',to_jsonb(x)-'character_id' FROM public.issue_reports x;
 END IF;
 IF EXISTS((SELECT * FROM c2_reset_preserved EXCEPT ALL SELECT * FROM c2_reset_after)
  UNION ALL (SELECT * FROM c2_reset_after EXCEPT ALL SELECT * FROM c2_reset_preserved)) THEN
  RAISE EXCEPTION 'C2 reset preserved data changed'; END IF;
END $reset$;
-- No COMMIT here. Corrected B follows under the SAME transaction and retained locks.


-- Component: progression-001G-C2-integrated-cutover.sql; SHA-256 7df1c1cd143433878019628d40d2bff6695df317e43cdb25105c1db31edf4fae
-- B: coordinated C2 cutover, NOT INSTALLED. Standard Drizzle ONE transaction.
-- Generated by scripts/prepare-c2-integrated-cutover.mjs; do not install components separately.

-- Component: progression-001G-C2-P2-B-cutover-containment.sql; SHA-256 925f8b62c7bf6b2a4980a150749df3e62f756c2be541e6c33e7411ce30c2c520
-- ACTIVATION-ONLY PREPARATION, NOT AUTHORIZATION. Standard tool, atomic transaction.
-- Stops old creation/deletion; bridge stays owner-only. No new public creation grant.
-- Run only in an approved creation/deletion maintenance window after inactive package.
DO $dependencies$
BEGIN
  IF to_regprocedure('public.character_create_c2(uuid,text,text,text,uuid,text,text)') IS NULL
    OR NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.character_materials'::regclass
      AND conname='character_materials_character_id_c2_fkey' AND contype='f')
  THEN RAISE EXCEPTION 'inactive P2-B package required'; END IF;
END $dependencies$;

-- Validate only; any orphan aborts this transaction. No automatic deletion/repair.
ALTER TABLE public.character_materials VALIDATE CONSTRAINT character_materials_character_id_c2_fkey;

-- Identified browser legacy caller and historical creation harnesses; retain owner access.
-- delete_character_cascade is deliberately disabled pending approved soft-delete lifecycle.
DO $functions$
DECLARE f record; grantee oid;
BEGIN
  FOR f IN SELECT p.oid,p.proowner,p.oid::regprocedure AS identity FROM pg_proc p
    JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public'
      AND p.proname IN ('character_create','c2_harness_run','c2_harness_run_c','delete_character_cascade') LOOP
    IF f.proowner<>'postgres'::regrole THEN RAISE EXCEPTION 'unexpected legacy function owner: %',f.identity; END IF;
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.identity);
    FOR grantee IN SELECT DISTINCT a.grantee FROM pg_proc p,LATERAL aclexplode(p.proacl) a
      WHERE p.oid=f.oid AND a.grantee<>p.proowner LOOP
      EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %s',f.identity,
        CASE WHEN grantee=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(grantee)) END);
    END LOOP;
    IF EXISTS (WITH RECURSIVE app(oid) AS (
      SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')
      UNION SELECT m.member FROM pg_auth_members m JOIN app ON m.roleid=app.oid)
      SELECT 1 FROM app WHERE oid<>f.proowner AND has_function_privilege(oid,f.oid,'EXECUTE'))
    THEN RAISE EXCEPTION 'legacy inherited execute leak: %',f.identity; END IF;
  END LOOP;
END $functions$;

-- No direct creation consumer found in current browser/Edge code; harnesses above
-- use postgres definer writes. Do not change protected/unprotected UPDATE grants.
REVOKE INSERT,DELETE ON TABLE public.characters FROM PUBLIC,anon,authenticated,service_role;
DO $characters_acl$
DECLARE col text; r oid;
BEGIN
  FOR col IN SELECT attname FROM pg_attribute WHERE attrelid='public.characters'::regclass
    AND attnum>0 AND NOT attisdropped LOOP
    EXECUTE format('REVOKE INSERT (%I) ON public.characters FROM PUBLIC,anon,authenticated,service_role',col);
  END LOOP;
  FOR r IN WITH RECURSIVE app(oid) AS (
    SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')
    UNION SELECT m.member FROM pg_auth_members m JOIN app ON m.roleid=app.oid)
    SELECT oid FROM app WHERE oid<>'postgres'::regrole LOOP
    IF has_table_privilege(r,'public.characters','INSERT,DELETE')
      OR has_any_column_privilege(r,'public.characters','INSERT')
    THEN RAISE EXCEPTION 'inherited direct creation/deletion leak: %',pg_get_userbyid(r); END IF;
    IF has_function_privilege(r,'public.character_create_c2(uuid,text,text,text,uuid,text,text)','EXECUTE')
    THEN RAISE EXCEPTION 'bridge must remain paused until lifecycle/activation gates clear'; END IF;
  END LOOP;
END $characters_acl$;


-- Component: progression-001G-C2-P2-C-runtime-exclusions.sql; SHA-256 15530c2f1d07934ce2987ed9c8a5a35bff46231376c07fecb79fdc93b2c0a12c
-- LOCAL ACTIVATION-ONLY preparation; standard tool, one transaction.
-- Exact hosted settlement chain: preserve outer wrapper; exclude tombstones in inner/helper loops.
-- CREATE OR REPLACE preserves existing function owners/ACLs. No new EXECUTE grants.
DO $source_guard$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.combat2_presence_heartbeat(uuid)'::regprocedure AND proowner='postgres'::regrole AND prosecdef AND proconfig @> ARRAY['search_path=public, auth, pg_temp'] AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='9e94b365242c34c90a76b85175d6b5f15be39e2df58f7826579194d137dda6e1') THEN RAISE EXCEPTION 'lifecycle runtime source drift: combat2_presence_heartbeat'; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.combat2_session_access(uuid,uuid)'::regprocedure AND proowner='postgres'::regrole AND prosecdef AND proconfig @> ARRAY['search_path=public, auth, cron, pg_temp'] AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='dffc702006532a07e660a96394bb0245be5aa0ea963a50bfdf5fb709f2c65851') THEN RAISE EXCEPTION 'lifecycle runtime source drift: combat2_session_access'; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.combat2_regenerate_force_shields(timestamptz,integer)'::regprocedure AND proowner='postgres'::regrole AND prosecdef AND provolatile='v' AND proconfig=ARRAY['search_path=public, pg_temp'] AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='bb2b219f099d6f78809ff1172f219518e5d20f3894dab8a06adddcf8ce1764d8' AND cardinality(proacl)=3 AND proacl @> ARRAY['postgres=X/postgres','service_role=X/postgres','sandbox_exec_gpclaklkaolyzfnooajt=X/postgres']::aclitem[]) THEN RAISE EXCEPTION 'lifecycle runtime source drift: combat2_regenerate_force_shields'; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.settle_out_of_combat_resources(timestamptz)'::regprocedure AND proowner='postgres'::regrole AND prosecdef AND provolatile='v' AND proconfig=ARRAY['search_path=public, cron, pg_temp'] AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='17185b0df23c90e8707a739249c7940324dd387d49f6ec300a7be1d58d99c183' AND cardinality(proacl)=3 AND proacl @> ARRAY['postgres=X/postgres','service_role=X/postgres','sandbox_exec_gpclaklkaolyzfnooajt=X/postgres']::aclitem[]) THEN RAISE EXCEPTION 'lifecycle runtime source drift: settle_out_of_combat_resources'; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.settle_out_of_combat_resources_without_character_stances(timestamptz)'::regprocedure AND proowner='postgres'::regrole AND prosecdef AND provolatile='v' AND proconfig=ARRAY['search_path=public, cron, pg_temp'] AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='69e507eb64d25d0559cfd4a37cfc4e3016b2201f221692a3326bb9c219d46e90' AND cardinality(proacl)=3 AND proacl @> ARRAY['postgres=X/postgres','service_role=X/postgres','sandbox_exec_gpclaklkaolyzfnooajt=X/postgres']::aclitem[]) THEN RAISE EXCEPTION 'lifecycle runtime source drift: settle_out_of_combat_resources_without_character_stances'; END IF;
END $source_guard$;

CREATE OR REPLACE FUNCTION public.combat2_presence_heartbeat(_character_id uuid)
RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,auth,pg_temp AS $$
DECLARE caller uuid:=auth.uid();
BEGIN
 IF caller IS NULL OR NOT EXISTS(SELECT 1 FROM public.characters c WHERE c.id=_character_id AND c.user_id=caller AND c.deleted_at IS NULL)
 THEN RETURN jsonb_build_object('ok',false,'kind','not_authorized'); END IF;
 INSERT INTO public.combat2_player_presence(character_id,user_id,seen_at) VALUES(_character_id,caller,clock_timestamp())
 ON CONFLICT(character_id) DO UPDATE SET user_id=EXCLUDED.user_id,seen_at=clock_timestamp();
 RETURN jsonb_build_object('ok',true,'kind','present');
END $$;

CREATE OR REPLACE FUNCTION public.combat2_session_access(_character_id uuid,_node_id uuid)
RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=public,auth,cron,pg_temp AS $$
DECLARE caller uuid:=auth.uid();arena uuid;scheduler jsonb;
BEGIN
 IF caller IS NULL OR NOT EXISTS(SELECT 1 FROM public.characters c WHERE c.id=_character_id AND c.user_id=caller AND c.current_node_id=_node_id AND c.deleted_at IS NULL)
 THEN RETURN jsonb_build_object('ok',false,'kind','not_authorized'); END IF;
 SELECT t.arena_id INTO arena FROM public.combat2_test_arena_node t JOIN public.combat2_test_arena a ON a.id=t.arena_id AND a.active WHERE t.node_id=_node_id AND t.active;
 IF EXISTS(SELECT 1 FROM public.combat2_test_arena_node t WHERE t.node_id=_node_id) THEN
  IF arena IS NULL OR NOT public.combat2_test_arena_access_allowed(caller,_character_id,_node_id)
  THEN RETURN jsonb_build_object('ok',false,'kind','not_authorized'); END IF;
 END IF;
 PERFORM pg_advisory_xact_lock(hashtext('combat2-production-activation'));
 UPDATE public.combat_config SET value='open' WHERE key='combat_mode' AND value IS DISTINCT FROM 'open';
 PERFORM public.wake_world();
 scheduler:=public.combat2_dispatch_scheduler_enable();
 IF COALESCE(scheduler->>'ok','false')<>'true' THEN
  PERFORM public.combat2_dispatch_scheduler_disable();
  UPDATE public.combat_config SET value='maintenance' WHERE key='combat_mode';
  PERFORM public.shutdown_world();
  RETURN jsonb_build_object('ok',false,'kind','access_check_failed');
 END IF;
 IF arena IS NULL THEN
  INSERT INTO public.combat2_player_presence(character_id,user_id,seen_at) VALUES(_character_id,caller,clock_timestamp())
  ON CONFLICT(character_id) DO UPDATE SET user_id=EXCLUDED.user_id,seen_at=clock_timestamp();
 ELSE
  INSERT INTO public.combat2_test_presence(arena_id,character_id,user_id,seen_at) VALUES(arena,_character_id,caller,clock_timestamp())
  ON CONFLICT(arena_id,character_id) DO UPDATE SET user_id=EXCLUDED.user_id,seen_at=clock_timestamp();
 END IF;
 RETURN jsonb_build_object('ok',true,'kind','allowed','node_id',_node_id,'scope',CASE WHEN arena IS NULL THEN 'ordinary_world' ELSE 'test_arena' END);
EXCEPTION WHEN OTHERS THEN RETURN jsonb_build_object('ok',false,'kind','access_check_failed');
END $$;

-- Outer wrapper is intentionally NOT replaced. Existing owners/ACLs remain unchanged.
CREATE OR REPLACE FUNCTION public.settle_out_of_combat_resources_without_character_stances(_now timestamp with time zone DEFAULT clock_timestamp())
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'cron', 'pg_temp'
AS $function$
DECLARE
  state public.character_resource_settlement_state%ROWTYPE;
  bucket timestamptz := date_bin(interval '4 seconds', _now, timestamptz 'epoch');
  elapsed integer;
  steps integer;
  c public.characters%ROWTYPE;
  bonus_hp integer;
  bonus_con integer;
  bonus_int integer;
  bonus_wis integer;
  bonus_dex integer;
  bonus_hp_regen integer;
  effective_con integer;
  effective_wis integer;
  effective_dex integer;
  con_mod integer;
  int_mod integer;
  wis_mod integer;
  dex_mod integer;
  base_hp integer;
  hp_cap integer;
  cp_cap integer;
  mp_cap integer;
  hp_per_tick integer;
  cp_per_tick integer;
  mp_per_tick integer;
  inn_bonus integer;
  eligible_count integer := 0;
  settled_count integer := 0;
BEGIN
  IF _now > clock_timestamp() + interval '5 seconds' THEN
    RETURN jsonb_build_object('ok', false, 'kind', 'invalid_time');
  END IF;

  SELECT * INTO state FROM public.character_resource_settlement_state
  WHERE singleton FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'resource settlement state missing'; END IF;

  -- Advancing the cursor while ineligible prevents sleep or maintenance time
  -- from becoming banked regeneration when the world next wakes.
  IF NOT public.world_state_is_awake()
     OR NOT public.combat_mode_is_open()
     OR NOT EXISTS (
       SELECT 1 FROM cron.job
       WHERE jobname = 'combat2-dispatch-once'
         AND schedule = '2 seconds'
         AND command = 'SELECT public.combat2_dispatch_scheduler_fire();'
     ) THEN
    UPDATE public.character_resource_settlement_state
      SET settled_bucket = GREATEST(settled_bucket, bucket), updated_at = clock_timestamp()
      WHERE singleton;
    RETURN jsonb_build_object('ok', false, 'kind', 'ineligible', 'steps', 0);
  END IF;

  elapsed := floor(extract(epoch FROM (bucket - state.settled_bucket)) / 4.0)::integer;
  IF elapsed <= 0 THEN
    RETURN jsonb_build_object('ok', true, 'kind', 'already_settled', 'steps', 0);
  END IF;
  -- Ordinary scheduler jitter catches up at most three four-second intervals.
  -- A longer gap represents downtime: award one current interval, never the gap.
  steps := CASE WHEN elapsed <= 3 THEN elapsed ELSE 1 END;
  UPDATE public.character_resource_settlement_state
    SET settled_bucket = bucket, updated_at = clock_timestamp() WHERE singleton;

  -- Lock order is character UUID only. No encounter row is locked here. Combat
  -- entry/commit/movement may lock encounter then character, so this cannot add
  -- a reversed encounter/character lock pair; after the character lock, all
  -- ownership and transition predicates are re-read before mutation.
  FOR c IN SELECT * FROM public.characters WHERE deleted_at IS NULL ORDER BY id FOR UPDATE LOOP
    IF c.hp <= 0 OR c.current_node_id IS NULL THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.combat2_test_arena_node t WHERE t.node_id = c.current_node_id) THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.combat2_departure_request d
      WHERE d.character_id = c.id AND (d.status = 'queued' OR d.resolved_at >= bucket)) THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.combat2_party_departure_member m
      JOIN public.combat2_party_departure_request r ON r.request_id = m.request_id
      WHERE m.character_id = c.id AND ((r.status = 'queued' AND m.status IN ('waiting','queued'))
        OR m.resolved_at >= bucket)) THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.combat2_respawn_request rr
      WHERE rr.character_id = c.id AND rr.created_at >= bucket) THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.node_fighter released
      WHERE released.character_id = c.id AND released.left_at >= bucket) THEN CONTINUE; END IF;
    IF EXISTS (SELECT 1 FROM public.node_fighter f
      JOIN public.node_encounter e ON e.id = f.encounter_id
      WHERE f.character_id = c.id AND e.status = 'active' AND (
        (f.present AND EXISTS (SELECT 1 FROM public.node_creature nc
          WHERE nc.encounter_id = e.id AND nc.is_alive AND nc.hp > 0 AND nc.engaged))
        OR (f.present AND e.claim_token IS NOT NULL AND e.claim_expires_at > _now)
      )) THEN CONTINUE; END IF;

    eligible_count := eligible_count + 1;
    SELECT
      COALESCE(sum(COALESCE((base->>'hp')::integer, 0)), 0)::integer,
      COALESCE(sum(COALESCE((base->>'con')::integer, 0) + COALESCE((gems->>'emerald')::integer, 0)), 0)::integer,
      COALESCE(sum(COALESCE((base->>'int')::integer, 0) + COALESCE((gems->>'sapphire')::integer, 0)), 0)::integer,
      COALESCE(sum(COALESCE((base->>'wis')::integer, 0) + COALESCE((gems->>'pearl')::integer, 0)), 0)::integer,
      COALESCE(sum(COALESCE((base->>'dex')::integer, 0) + COALESCE((gems->>'topaz')::integer, 0)), 0)::integer,
      COALESCE(sum(COALESCE((base->>'hp_regen')::integer, 0)), 0)::integer
    INTO bonus_hp, bonus_con, bonus_int, bonus_wis, bonus_dex, bonus_hp_regen
    FROM (
      SELECT COALESCE(NULLIF(ci.stat_override, '{}'::jsonb), i.stats, '{}'::jsonb) base,
             COALESCE(ci.applied_gems, '{}'::jsonb) gems
      FROM public.character_inventory ci JOIN public.items i ON i.id = ci.item_id
      WHERE ci.character_id = c.id AND ci.equipped_slot IS NOT NULL AND ci.current_durability > 0
    ) equipped;

    effective_con := c.con + bonus_con;
    effective_wis := c.wis + bonus_wis;
    effective_dex := c.dex + bonus_dex;
    con_mod := floor((effective_con - 10) / 2.0)::integer;
    int_mod := greatest(floor(((c.int + bonus_int) - 10) / 2.0)::integer, 0);
    wis_mod := greatest(floor((effective_wis - 10) / 2.0)::integer, 0);
    dex_mod := greatest(floor((effective_dex - 10) / 2.0)::integer, 0);
    base_hp := CASE c.class::text WHEN 'warrior' THEN 24 WHEN 'wizard' THEN 16
      WHEN 'ranger' THEN 20 WHEN 'rogue' THEN 16 WHEN 'assassin' THEN 16
      WHEN 'healer' THEN 18 WHEN 'bard' THEN 16 WHEN 'templar' THEN 22 ELSE 18 END;
    hp_cap := least(greatest(base_hp + con_mod * 2 + (c.level - 1) * 5 + bonus_hp, 1), 10000);
    cp_cap := least(greatest(30 + (c.level - 1) * 3 + (int_mod + wis_mod) * 3, 0), 5000);
    mp_cap := least(greatest(100 + dex_mod * 10 + floor((c.level - 1) * 2)::integer, 0), 5000);
    SELECT CASE WHEN n.is_inn THEN 10 ELSE 0 END INTO inn_bonus
      FROM public.nodes n WHERE n.id = c.current_node_id;
    inn_bonus := COALESCE(inn_bonus, 0);

    hp_per_tick := 2 + floor(sqrt(greatest(effective_con - 10, 0)))::integer
      + bonus_hp_regen + CASE WHEN c.level >= 40 THEN 10 WHEN c.level >= 35 THEN 8
        WHEN c.level >= 30 THEN 6 WHEN c.level >= 25 THEN 4 WHEN c.level >= 20 THEN 2 ELSE 0 END
      + inn_bonus;
    cp_per_tick := 2 + floor(sqrt(greatest(effective_wis - 10, 0)))::integer
      + CASE WHEN c.level >= 40 THEN 5 WHEN c.level >= 35 THEN 4 WHEN c.level >= 30 THEN 3
        WHEN c.level >= 25 THEN 2 WHEN c.level >= 20 THEN 1 ELSE 0 END + inn_bonus;
    mp_per_tick := round((5 + dex_mod) * 0.67)::integer * 2 + inn_bonus;

    PERFORM set_config('app.trusted_rpc', 'true', true);
    UPDATE public.characters SET
      hp = CASE WHEN hp < hp_cap THEN least(hp_cap, hp + hp_per_tick * steps) ELSE hp END,
      cp = CASE WHEN cp < cp_cap THEN least(cp_cap, cp + cp_per_tick * steps) ELSE cp END,
      mp = CASE WHEN mp < mp_cap THEN least(mp_cap, mp + mp_per_tick * steps) ELSE mp END
    WHERE id = c.id AND hp > 0;
    IF FOUND THEN settled_count := settled_count + 1; END IF;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'kind', 'settled', 'steps', steps,
    'eligible_count', eligible_count, 'settled_count', settled_count, 'bucket', bucket);
END;
$function$;

CREATE OR REPLACE FUNCTION public.combat2_regenerate_force_shields(_now timestamp with time zone, _settlement_steps integer)
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'pg_temp'
AS $function$
DECLARE row record; bonus_int integer; bonus_wis integer; int_mod integer; wis_mod integer;
 cap integer; per_tick integer; changed integer:=0;
BEGIN
 IF _settlement_steps<=0 THEN RETURN 0; END IF;
 FOR row IN SELECT c.*,s.state,s.version FROM public.characters c JOIN public.character_stance s ON s.character_id=c.id
  WHERE s.ability_key='force_shield' AND c.deleted_at IS NULL ORDER BY c.id FOR UPDATE OF c,s LOOP
   IF row.hp<=0 OR row.current_node_id IS NULL
      OR EXISTS(SELECT 1 FROM public.combat2_test_arena_node t WHERE t.node_id=row.current_node_id)
      OR EXISTS(SELECT 1 FROM public.combat2_departure_request d WHERE d.character_id=row.id
        AND (d.status='queued' OR d.resolved_at>=date_bin(interval '4 seconds',_now,timestamptz 'epoch')))
      OR EXISTS(SELECT 1 FROM public.combat2_party_departure_member m JOIN public.combat2_party_departure_request r ON r.request_id=m.request_id
        WHERE m.character_id=row.id AND ((r.status='queued' AND m.status IN('waiting','queued'))
          OR m.resolved_at>=date_bin(interval '4 seconds',_now,timestamptz 'epoch')))
      OR EXISTS(SELECT 1 FROM public.combat2_respawn_request rr WHERE rr.character_id=row.id
        AND rr.created_at>=date_bin(interval '4 seconds',_now,timestamptz 'epoch'))
      OR EXISTS(SELECT 1 FROM public.node_fighter released WHERE released.character_id=row.id
        AND released.left_at>=date_bin(interval '4 seconds',_now,timestamptz 'epoch'))
      OR EXISTS(SELECT 1 FROM public.node_fighter f JOIN public.node_encounter e ON e.id=f.encounter_id
        WHERE f.character_id=row.id AND e.status='active' AND ((f.present AND EXISTS(
          SELECT 1 FROM public.node_creature nc WHERE nc.encounter_id=e.id AND nc.is_alive AND nc.hp>0 AND nc.engaged))
          OR (e.claim_token IS NOT NULL AND e.claim_expires_at>_now))) THEN CONTINUE; END IF;
   SELECT coalesce(sum(coalesce((coalesce(nullif(ci.stat_override,'{}'::jsonb),i.stats,'{}'::jsonb)->>'int')::integer,0)
       +coalesce((coalesce(ci.applied_gems,'{}'::jsonb)->>'sapphire')::integer,0)),0)::integer,
     coalesce(sum(coalesce((coalesce(nullif(ci.stat_override,'{}'::jsonb),i.stats,'{}'::jsonb)->>'wis')::integer,0)
       +coalesce((coalesce(ci.applied_gems,'{}'::jsonb)->>'pearl')::integer,0)),0)::integer
     INTO bonus_int,bonus_wis FROM public.character_inventory ci JOIN public.items i ON i.id=ci.item_id
     WHERE ci.character_id=row.id AND ci.equipped_slot IS NOT NULL AND ci.current_durability>0;
   int_mod:=greatest(0,floor(((row.int+bonus_int)-10)/2.0)::integer);
   wis_mod:=greatest(0,floor(((row.wis+bonus_wis)-10)/2.0)::integer);
   cap:=greatest(1,wis_mod+floor(row.level/2.0)::integer); per_tick:=1+floor(int_mod/2.0)::integer;
   UPDATE public.character_stance SET state=jsonb_set(state,'{ward_remaining}',to_jsonb(least(cap,
       greatest(0,coalesce((state->>'ward_remaining')::integer,cap))+(_settlement_steps*2*per_tick))),true),
     version=version+1,updated_at=clock_timestamp()
    WHERE character_id=row.id AND ability_key='force_shield' AND version=row.version
      AND greatest(0,coalesce((state->>'ward_remaining')::integer,cap))<cap;
   IF FOUND THEN changed:=changed+1; END IF;
 END LOOP;
 RETURN changed;
END $function$;


-- Component: progression-001G-C2-integrated-family-guard.sql; SHA-256 71920f43e0f4023ddc2777b8a60a2e57083ee64e6cc726f79f20217200f3c7c4
-- Activation-only approved C2-04: no family at creation, L10 founding / L1 joining.
-- Existing function signature/owner/ACL retained, no new grants. Drift aborts.
DO $guard$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.apply_family_to_character(uuid,text)'::regprocedure
    AND proowner='postgres'::regrole AND prosecdef AND proconfig @> ARRAY['search_path=public']
    AND encode(sha256(convert_to(replace(prosrc,E'\r\n',E'\n'),'UTF8')),'hex')='da44f7162bd0104a77a6f3f7d2b03d2fcc7689f04f4b930d036362b4e53ee91e')
  THEN RAISE EXCEPTION 'family source drift; inspect instead of overwriting'; END IF;
END $guard$;

CREATE OR REPLACE FUNCTION public.apply_family_to_character(
  _character_id UUID,
  _display TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  _key TEXT;
  _family_id UUID;
  _family_display TEXT;
  _founder UUID;
  _is_member BOOLEAN;
  _char RECORD;
  _hash BIGINT;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  SELECT id, user_id, family_name, family_changed_after_creation, level, deleted_at
    INTO _char
    FROM public.characters WHERE id = _character_id FOR UPDATE;
  IF NOT FOUND OR _char.user_id <> auth.uid() OR _char.deleted_at IS NOT NULL THEN
    RAISE EXCEPTION 'Character not found';
  END IF;

  -- Clearing family name
  IF _display IS NULL OR length(btrim(_display)) = 0 THEN
    UPDATE public.characters
      SET family_name = NULL, family_id = NULL
      WHERE id = _character_id;
    RETURN jsonb_build_object('ok', true, 'cleared', true);
  END IF;

  IF _display !~ '^[A-Za-z]{2,20}$' THEN
    RAISE EXCEPTION 'Family name must be 2-20 letters';
  END IF;
  _key := lower(_display);
  IF public._family_name_is_reserved(_key) THEN
    RAISE EXCEPTION 'That family name is reserved';
  END IF;

  -- advisory lock keyed on the family name to make the founder claim atomic
  _hash := abs(hashtextextended(_key, 0));
  PERFORM pg_advisory_xact_lock(_hash);

  SELECT id, display_name, founder_user_id
    INTO _family_id, _family_display, _founder
    FROM public.families WHERE key = _key;

  IF NOT FOUND THEN
    IF _char.level < 10 THEN RAISE EXCEPTION 'Family founding requires level 10'; END IF;
    INSERT INTO public.families (key, display_name, founder_user_id)
      VALUES (_key, _display, auth.uid())
      RETURNING id, display_name, founder_user_id INTO _family_id, _family_display, _founder;
  ELSE
    IF _founder <> auth.uid() THEN
      SELECT EXISTS(
        SELECT 1 FROM public.family_members
        WHERE family_id = _family_id AND user_id = auth.uid()
      ) INTO _is_member;
      IF NOT _is_member THEN
        RAISE EXCEPTION 'You are not a member of the % family', _family_display;
      END IF;
    END IF;
  END IF;

  UPDATE public.characters
    SET family_name = _family_display,
        family_id = _family_id
    WHERE id = _character_id;

  RETURN jsonb_build_object(
    'ok', true,
    'family_id', _family_id,
    'display_name', _family_display,
    'founded', (_founder = auth.uid())
  );
END;
$$;


-- Component: progression-001G-C2-P2-C-lifecycle-cutover.sql; SHA-256 2ef9cfe0c3cd913ca78200e18815e0a1e48320d6dcb7112c1e78438204726b52
-- LOCAL ACTIVATION-ONLY INPUT, not installed. Standard tool, one transaction.
-- Replaces deletion only; creation bridge/internal functions stay owner-only.
-- Review gameplay/selection and expiry-maintenance gates in P2-C handoff first.
DO $dependencies$
BEGIN
  IF to_regprocedure('public.character_lifecycle_command(uuid,uuid,bigint,text,text)') IS NULL
    OR EXISTS(SELECT 1 FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')
      AND (has_function_privilege(oid,'public.character_create_c2(uuid,text,text,text,uuid,text,text)','EXECUTE')
        OR has_function_privilege(oid,'public.character_create_c2_internal(uuid,text,text,text,uuid,text,text)','EXECUTE')))
  THEN RAISE EXCEPTION 'private lifecycle/paused creation dependency drift'; END IF;
  -- Otherwise legacy client-stat creation/direct INSERT could bypass the all-retained
  -- quota after tombstones disappear from the old selection UI. Do not enable C2 here.
  IF EXISTS(SELECT 1 FROM pg_roles r WHERE r.rolname IN ('anon','authenticated','service_role')
      AND (has_table_privilege(r.oid,'public.characters','INSERT')
        OR has_any_column_privilege(r.oid,'public.characters','INSERT')))
    OR EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
      CROSS JOIN pg_roles r WHERE n.nspname='public' AND p.proname='character_create'
        AND r.rolname IN ('anon','authenticated','service_role') AND has_function_privilege(r.oid,p.oid,'EXECUTE'))
  THEN RAISE EXCEPTION 'lifecycle cutover requires prior legacy creation containment'; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.settle_out_of_combat_resources_without_character_stances(timestamptz)'::regprocedure
    AND prosrc LIKE '%FROM public.characters WHERE deleted_at IS NULL ORDER BY id FOR UPDATE%')
    OR NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.settle_out_of_combat_resources(timestamptz)'::regprocedure
      AND prosrc LIKE '%public.settle_out_of_combat_resources_without_character_stances(_now)%'
      AND prosrc LIKE '%public.combat2_regenerate_force_shields(_now,%')
    OR NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='public.combat2_regenerate_force_shields(timestamptz,integer)'::regprocedure
      AND prosrc LIKE '%c.deleted_at IS NULL%')
    OR EXISTS(SELECT 1 FROM pg_proc WHERE oid IN ('public.combat2_session_access(uuid,uuid)'::regprocedure,
      'public.combat2_presence_heartbeat(uuid)'::regprocedure) AND prosrc NOT LIKE '%c.deleted_at IS NULL%')
  THEN RAISE EXCEPTION 'lifecycle runtime exclusions must precede cutover'; END IF;
END $dependencies$;

CREATE FUNCTION public.character_lifecycle_character_fence() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
  -- Only the receipt inserted by the authorized purge in this exact transaction.
  -- No GUC/trigger-disable escape hatch; old receipts cannot authorize raw deletion.
  IF TG_OP='DELETE' THEN
    IF current_user<>'postgres' OR OLD.deleted_at IS NULL OR clock_timestamp()<OLD.restore_until
      OR NOT EXISTS(SELECT 1 FROM public.character_lifecycle_receipt r
        WHERE r.character_id=OLD.id AND r.owner_account_id=OLD.user_id
          AND r.operation='purge' AND r.expected_version=OLD.lifecycle_version
          AND r.actor_id=auth.uid() AND r.reason IS NOT NULL AND r.result->>'kind'='purged'
          AND r.purge_transaction=pg_current_xact_id())
    THEN RAISE EXCEPTION 'lifecycle_physical_purge_not_authorized'; END IF;
    RETURN OLD;
  END IF;
  IF TG_OP='INSERT' THEN
    IF EXISTS(SELECT 1 FROM public.character_lifecycle_receipt WHERE character_id=NEW.id AND operation='purge')
      OR EXISTS(SELECT 1 FROM public.character_creation_log WHERE result_character_id=NEW.id AND replay_status='purged')
    THEN RAISE EXCEPTION 'lifecycle_purged_identity_reserved'; END IF;
    IF NEW.deleted_at IS NOT NULL OR NEW.restore_until IS NOT NULL OR NEW.lifecycle_version<>0
    THEN RAISE EXCEPTION 'lifecycle_insert_tombstone_forbidden'; END IF;
    RETURN NEW;
  END IF;
  IF ROW(NEW.deleted_at,NEW.restore_until,NEW.lifecycle_version)
    IS DISTINCT FROM ROW(OLD.deleted_at,OLD.restore_until,OLD.lifecycle_version) THEN
    IF current_user<>'postgres' OR NEW.lifecycle_version<>OLD.lifecycle_version+1
      OR to_jsonb(NEW)-ARRAY['deleted_at','restore_until','lifecycle_version']
        IS DISTINCT FROM to_jsonb(OLD)-ARRAY['deleted_at','restore_until','lifecycle_version']
      OR NOT EXISTS(SELECT 1 FROM public.character_lifecycle_receipt r
        WHERE r.character_id=OLD.id AND r.owner_account_id=OLD.user_id AND r.expected_version=OLD.lifecycle_version
          AND r.result->>'version'=NEW.lifecycle_version::text
          AND (r.result->>'deletedAt')::timestamptz IS NOT DISTINCT FROM NEW.deleted_at
          AND (r.result->>'restoreUntil')::timestamptz IS NOT DISTINCT FROM NEW.restore_until
          AND r.operation=CASE WHEN NEW.deleted_at IS NULL THEN 'restore' ELSE 'soft_delete' END)
    THEN RAISE EXCEPTION 'lifecycle_transition_not_authorized'; END IF;
  ELSIF OLD.deleted_at IS NOT NULL THEN
    RAISE EXCEPTION 'character_soft_deleted';
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER character_lifecycle_character_fence BEFORE INSERT OR UPDATE OR DELETE ON public.characters
  FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_character_fence();

CREATE FUNCTION public.character_lifecycle_child_fence() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE data jsonb; col text; subject uuid; deleted timestamptz;
BEGIN
  -- Check both source and destination of a transfer; holds row locks to transaction end.
  FOR data IN SELECT x FROM unnest(ARRAY[
    CASE WHEN TG_OP<>'INSERT' THEN to_jsonb(OLD) ELSE NULL END,
    CASE WHEN TG_OP<>'DELETE' THEN to_jsonb(NEW) ELSE NULL END]) x WHERE x IS NOT NULL LOOP
    FOREACH col IN ARRAY TG_ARGV LOOP
      subject:=(data->>col)::uuid;
      IF subject IS NOT NULL THEN
        SELECT deleted_at INTO deleted FROM public.characters WHERE characters.id=subject FOR KEY SHARE;
        IF FOUND AND deleted IS NOT NULL AND NOT (TG_OP IN ('UPDATE','DELETE') AND EXISTS(
          SELECT 1 FROM public.character_lifecycle_receipt r WHERE r.character_id=subject AND r.operation='purge'
            AND r.actor_id=auth.uid() AND r.reason IS NOT NULL AND r.result->>'kind'='purged'
            AND r.purge_transaction=pg_current_xact_id()))
        THEN RAISE EXCEPTION 'character_soft_deleted'; END IF;
        -- Shared creature/character target columns may legitimately name a creature.
        -- FK/normal domain authorities, not this fence, validate missing/other targets.
      END IF;
    END LOOP;
  END LOOP;
  RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END $$;

DO $child_fences$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'character_materials','character_inventory','character_class_bonds','character_visited_nodes',
    'character_stance','character_stance_request','progression_character_state','progression_receipt',
    'progression_respec_milestone','progression_class_growth_milestone',
    'node_fighter','node_intent','node_reward_claim','combat_sessions','party_members',
    'combat2_departure_request','combat2_party_departure_member'] LOOP
    -- Mandatory source dependencies. Missing objects/columns must abort, not be skipped.
    IF NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=('public.'||table_name)::regclass
      AND attname='character_id' AND atttypid='uuid'::regtype AND NOT attisdropped)
    THEN RAISE EXCEPTION 'lifecycle child dependency drift: %',table_name; END IF;
    EXECUTE format('CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.%I
      FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence(''character_id'')',table_name);
  END LOOP;
END $child_fences$;
DO $other_children$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['character_ability_loadout','character_inventory_action_request',
    'character_special_travel_request','character_waymark','character_npc_gifts','character_guide_reads',
    'hidden_path_search_request','combat2_player_presence','combat2_test_presence',
    'combat_audit_log','combat_soak_access','combat2_diagnostic_session','combat2_respawn_request',
    'combat2_test_arena_access','combat2_test_arena_stance_snapshot_header',
    'encounter_access_grants','encounter_engagements','encounter_participants','node_participation'] LOOP
    IF NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=('public.'||table_name)::regclass
      AND attname='character_id' AND atttypid='uuid'::regtype AND NOT attisdropped)
    THEN RAISE EXCEPTION 'lifecycle child dependency drift: %',table_name; END IF;
    EXECUTE format('CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.%I
      FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence(''character_id'')',table_name);
  END LOOP;
END $other_children$;
CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.combat_actions
  FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence('character_id','target_character_id');
CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.node_effect
  FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence('target_character_id','source_character_id');
CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.marketplace_listings
  FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence('seller_character_id','buyer_character_id');
CREATE TRIGGER character_lifecycle_child_fence BEFORE INSERT OR UPDATE OR DELETE ON public.active_effects
  FOR EACH ROW EXECUTE FUNCTION public.character_lifecycle_child_fence('target_id','source_id');

-- Additive restrictive policy: do not replace the existing ownership/steward policies.
CREATE POLICY characters_lifecycle_active_read ON public.characters AS RESTRICTIVE FOR SELECT
  TO anon,authenticated USING(deleted_at IS NULL);

DO $private_trigger_acl$
DECLARE f record; g oid;
BEGIN
  FOR f IN SELECT p.oid,p.oid::regprocedure AS identity FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public' AND p.proname IN ('character_lifecycle_character_fence','character_lifecycle_child_fence') LOOP
    EXECUTE format('ALTER FUNCTION %s OWNER TO postgres',f.identity);
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f.identity);
    FOR g IN SELECT DISTINCT a.grantee FROM pg_proc p,LATERAL aclexplode(p.proacl) a
      WHERE p.oid=f.oid AND a.grantee<>p.proowner LOOP
      EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %s',f.identity,
        CASE WHEN g=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(g)) END);
    END LOOP;
  END LOOP;
END $private_trigger_acl$;

-- Only confirmed hard-delete RPC and direct parent DELETE; no unrelated UPDATE changes.
DO $legacy_delete_acl$
DECLARE f oid; g oid; r oid;
BEGIN
  FOR f IN SELECT p.oid FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public' AND p.proname IN ('delete_character_cascade','c2_harness_run','c2_harness_run_c') LOOP
  IF (SELECT proowner FROM pg_proc WHERE oid=f)<>'postgres'::regrole
  THEN RAISE EXCEPTION 'legacy delete owner drift'; END IF;
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,anon,authenticated,service_role',f::regprocedure);
  FOR g IN SELECT DISTINCT a.grantee FROM pg_proc p,LATERAL aclexplode(p.proacl) a
    WHERE p.oid=f AND a.grantee<>p.proowner LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %s',f::regprocedure,
      CASE WHEN g=0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(g)) END);
  END LOOP;
  FOR r IN WITH RECURSIVE app(oid) AS (
    SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')
    UNION SELECT m.member FROM pg_auth_members m JOIN app ON m.roleid=app.oid)
    SELECT oid FROM app WHERE oid<>'postgres'::regrole LOOP
    IF has_function_privilege(r,f,'EXECUTE') THEN RAISE EXCEPTION 'lifecycle legacy EXECUTE leak'; END IF;
  END LOOP;
  END LOOP;
  REVOKE DELETE,TRUNCATE ON public.characters FROM PUBLIC,anon,authenticated,service_role;
  FOR r IN WITH RECURSIVE app(oid) AS (
    SELECT oid FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')
    UNION SELECT m.member FROM pg_auth_members m JOIN app ON m.roleid=app.oid)
    SELECT oid FROM app WHERE oid<>'postgres'::regrole LOOP
    IF has_table_privilege(r,'public.characters','DELETE,TRUNCATE')
    THEN RAISE EXCEPTION 'lifecycle hard-delete privilege leak: %',pg_get_userbyid(r); END IF;
  END LOOP;
END $legacy_delete_acl$;

-- Application access goes through runtime owner/Overlord checks, never direct fields/storage.
GRANT EXECUTE ON FUNCTION public.character_lifecycle_command(uuid,uuid,bigint,text,text) TO authenticated;
DO $public_boundary$
BEGIN
  IF has_function_privilege('anon','public.character_lifecycle_command(uuid,uuid,bigint,text,text)','EXECUTE')
    OR has_function_privilege('service_role','public.character_lifecycle_command(uuid,uuid,bigint,text,text)','EXECUTE')
  THEN RAISE EXCEPTION 'lifecycle command execution boundary drift'; END IF;
END $public_boundary$;


-- Component: progression-001G-C2-integrated-enable.sql; SHA-256 ebacf7073010fc86d0a978684c982ff1280210e64881f4501fd03a4c2e5590d5
-- Last component of B, never install alone. All B components must share ONE transaction.
DO $gates$
BEGIN
  IF current_user<>'postgres' OR NOT has_table_privilege(current_user,'auth.users','TRIGGER')
    OR NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='public.characters'::regclass
      AND tgname='character_lifecycle_character_fence' AND NOT tgisinternal AND tgenabled='O')
    OR to_regprocedure('public.character_receipt_maintenance_internal()') IS NULL
  THEN RAISE EXCEPTION 'integrated support / lifecycle fence / auth trigger privilege required'; END IF;
  IF EXISTS(SELECT 1 FROM pg_trigger WHERE tgrelid='auth.users'::regclass AND tgname='character_c2_account_deleted')
  THEN RAISE EXCEPTION 'account trigger namespace conflict'; END IF;
END $gates$;
CREATE TRIGGER character_c2_account_deleted AFTER DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.character_account_deleted_internal();

-- Administrative retention housekeeping, not a gameplay heartbeat or auto purge.
DO $maintenance$
BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_cron')
    OR to_regprocedure('cron.schedule(text,text,text)') IS NULL
  THEN RAISE EXCEPTION 'existing pg_cron required; do not install a new runner'; END IF;
  IF EXISTS(SELECT 1 FROM cron.job WHERE jobname='character-c2-receipt-expiry')
  THEN RAISE EXCEPTION 'receipt maintenance job already exists'; END IF;
  PERFORM cron.schedule('character-c2-receipt-expiry','17 3 * * *',
    'SELECT public.character_receipt_maintenance_internal();');
END $maintenance$;

GRANT EXECUTE ON FUNCTION public.character_create_c2(uuid,text,text,text,uuid,text,text),
  public.character_creation_capacity(uuid) TO authenticated;
DO $boundary$
DECLARE f oid; r oid;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'public.character_create_c2(uuid,text,text,text,uuid,text,text)'::regprocedure::oid,
    'public.character_creation_capacity(uuid)'::regprocedure::oid,
    'public.character_lifecycle_command(uuid,uuid,bigint,text,text)'::regprocedure::oid] LOOP
    IF NOT has_function_privilege('authenticated',f,'EXECUTE')
      OR has_function_privilege('anon',f,'EXECUTE') OR has_function_privilege('service_role',f,'EXECUTE')
    THEN RAISE EXCEPTION 'integrated public execution boundary drift'; END IF;
  END LOOP;
END $boundary$;
