-- READ ONLY: one-time CHARACTER reset dependency intake, NOT reset execution.
-- Do not read Auth secrets, renown key material, world configuration values or row payloads.
-- Candidate classification is SOURCE ONLY, not an executable deletion allowlist.
WITH candidates(name,classification) AS (VALUES
('active_effects','1 — reset permitted temporary runtime'),
('character_ability_loadout','1 — reset completely (candidate)'),
('character_class_bonds','1 — reset completely (candidate)'),
('character_creation_log','1 — reset completely (candidate)'),
('character_creation_origin','1 — reset completely (candidate)'),
('character_guide_reads','1 — reset completely (candidate)'),
('character_inventory','1 — reset completely (candidate)'),
('character_inventory_action_request','1 — reset completely (candidate)'),
('character_lifecycle_receipt','1 — reset completely (candidate)'),
('character_materials','1 — reset completely (candidate)'),
('character_npc_gifts','1 — reset completely (candidate)'),
('character_resource_settlement_state','3 — preserve'),
('character_special_travel_request','1 — reset completely (candidate)'),
('character_stance','1 — reset completely (candidate)'),
('character_stance_request','1 — reset completely (candidate)'),
('character_visited_nodes','1 — reset completely (candidate)'),
('character_waymark','1 — reset completely (candidate)'),
('characters','1 — reset completely (candidate)'),
('combat2_canary_node','3 — preserve'),
('combat2_departure_request','1 — reset completely (candidate)'),
('combat2_diagnostic_server_event','1 — reset completely (candidate)'),
('combat2_diagnostic_session','1 — reset completely (candidate)'),
('combat2_dispatch_schedule_state','3 — preserve'),
('combat2_party_departure_member','1 — reset completely (candidate)'),
('combat2_party_departure_request','1 — reset completely (candidate)'),
('combat2_player_presence','1 — reset completely (candidate)'),
('combat2_respawn_config','3 — preserve'),
('combat2_respawn_request','1 — reset completely (candidate)'),
('combat2_test_arena','3 — preserve'),
('combat2_test_arena_access','1 — reset completely (candidate)'),
('combat2_test_arena_creature','3 — preserve'),
('combat2_test_arena_node','3 — preserve'),
('combat2_test_arena_request','3 — preserve account admin replay'),
('combat2_test_arena_stance_snapshot','1 — reset completely (candidate)'),
('combat2_test_arena_stance_snapshot_header','1 — reset completely (candidate)'),
('combat2_test_presence','1 — reset completely (candidate)'),
('combat2_test_run','2 — preserve completed archives; remove active-run subset'),
('combat2_test_run_batch','2 — preserve completed archives; remove active-run subset'),
('combat2_test_run_event','2 — preserve completed archives; remove active-run subset'),
('combat2_tick_notification','1 — reset permitted temporary runtime'),
('combat_actions','1 — reset completely (candidate)'),
('combat_audit_log','1 — reset completely (candidate)'),
('combat_config','3 — preserve'),
('combat_sessions','1 — reset completely (candidate)'),
('combat_soak_access','1 — reset completely (candidate)'),
('combat_soak_scopes','1 — reset permitted temporary runtime'),
('effects_catchup_dispatch','1 — reset permitted temporary runtime'),
('effects_catchup_log','1 — reset permitted temporary runtime'),
('encounter_access_grants','1 — reset completely (candidate)'),
('encounter_cast_events','1 — reset permitted temporary runtime'),
('encounter_contributions','1 — reset completely (candidate)'),
('encounter_creatures','1 — reset permitted temporary runtime'),
('encounter_death_loot','1 — reset permitted temporary runtime'),
('encounter_engagements','1 — reset completely (candidate)'),
('encounter_kill_awards','1 — reset completely (candidate)'),
('encounter_participants','1 — reset completely (candidate)'),
('encounter_tick_batches','1 — reset permitted temporary runtime'),
('encounters','1 — reset permitted temporary runtime'),
('families','3 — preserve'),
('family_members','3 — preserve'),
('family_requests','3 — preserve'),
('hidden_path_search_request','1 — reset completely (candidate)'),
('issue_reports','2 — preserve account reports; unlink character fields'),
('marketplace_listings','1 — reset character escrow via existing holder triggers'),
('node_arrival_group','1 — reset permitted temporary runtime'),
('node_boss_ability_cooldown','1 — reset permitted temporary runtime'),
('node_creature','1 — reset permitted temporary runtime'),
('node_death_loot','1 — reset permitted temporary runtime'),
('node_effect','1 — reset permitted temporary runtime'),
('node_encounter','1 — reset permitted temporary runtime'),
('node_fighter','1 — reset completely (candidate)'),
('node_ground_loot','1 — reset ALL temporary ground loot (owner approved)'),
('node_intent','1 — reset completely (candidate)'),
('node_participation','1 — reset completely (candidate)'),
('node_pending_event','1 — reset permitted temporary runtime'),
('node_reward_claim','1 — reset completely (candidate)'),
('node_tick_batch','1 — reset permitted temporary runtime'),
('node_tick_log','1 — reset permitted temporary runtime'),
('parties','1 — reset completely (candidate)'),
('party_combat_log','1 — reset completely (candidate)'),
('party_members','1 — reset completely (candidate)'),
('party_operation_request','1 — reset completely (candidate)'),
('progression_character_state','1 — reset completely (candidate)'),
('progression_class_growth_milestone','1 — reset completely (candidate)'),
('progression_command_control','3 — preserve'),
('progression_receipt','1 — reset completely (candidate)'),
('progression_renown_key','3 — preserve'),
('progression_respec_milestone','1 — reset completely (candidate)'),
('summon_requests','1 — reset completely (candidate)'),
('unique_item_instance','1 — reset obsolete runtime registry; preserve configured placements'),
('world_slumber_log','3 — preserve')
)
SELECT c.name,c.classification,to_regclass('public.'||quote_ident(c.name)) relation,
 t.relkind,t.relispartition,t.relrowsecurity,t.relforcerowsecurity,
 pg_get_userbyid(t.relowner) owner,
 CASE WHEN t.oid IS NOT NULL THEN row_security_active(t.oid) END inspector_rls_active,
 CASE WHEN t.oid IS NOT NULL THEN has_table_privilege(current_user,t.oid,'SELECT') END inspector_select
FROM candidates c LEFT JOIN pg_class t ON t.oid=to_regclass('public.'||quote_ident(c.name)) ORDER BY c.name;

-- Actual incoming reset-target FK closure, including nested cross-domain dependencies.
WITH RECURSIVE graph(oid) AS (
 SELECT to_regclass('public.'||quote_ident(v.name))::oid FROM (VALUES
('active_effects'),
('character_ability_loadout'),
('character_class_bonds'),
('character_creation_log'),
('character_creation_origin'),
('character_guide_reads'),
('character_inventory'),
('character_inventory_action_request'),
('character_lifecycle_receipt'),
('character_materials'),
('character_npc_gifts'),
('character_special_travel_request'),
('character_stance'),
('character_stance_request'),
('character_visited_nodes'),
('character_waymark'),
('characters'),
('combat2_departure_request'),
('combat2_diagnostic_server_event'),
('combat2_diagnostic_session'),
('combat2_party_departure_member'),
('combat2_party_departure_request'),
('combat2_player_presence'),
('combat2_respawn_request'),
('combat2_test_arena_access'),
('combat2_test_arena_stance_snapshot'),
('combat2_test_arena_stance_snapshot_header'),
('combat2_test_presence'),
('combat2_tick_notification'),
('combat_actions'),
('combat_audit_log'),
('combat_sessions'),
('combat_soak_access'),
('combat_soak_scopes'),
('effects_catchup_dispatch'),
('effects_catchup_log'),
('encounter_access_grants'),
('encounter_cast_events'),
('encounter_contributions'),
('encounter_creatures'),
('encounter_death_loot'),
('encounter_engagements'),
('encounter_kill_awards'),
('encounter_participants'),
('encounter_tick_batches'),
('encounters'),
('hidden_path_search_request'),
('marketplace_listings'),
('node_arrival_group'),
('node_boss_ability_cooldown'),
('node_creature'),
('node_death_loot'),
('node_effect'),
('node_encounter'),
('node_fighter'),
('node_ground_loot'),
('node_intent'),
('node_participation'),
('node_pending_event'),
('node_reward_claim'),
('node_tick_batch'),
('node_tick_log'),
('parties'),
('party_combat_log'),
('party_members'),
('party_operation_request'),
('progression_character_state'),
('progression_class_growth_milestone'),
('progression_receipt'),
('progression_respec_milestone'),
('summon_requests'),
('unique_item_instance')
 ) v(name) WHERE to_regclass('public.'||quote_ident(v.name)) IS NOT NULL
 UNION SELECT f.conrelid FROM pg_constraint f JOIN graph g ON g.oid=f.confrelid WHERE f.contype='f'
)
SELECT f.conrelid::regclass child,f.confrelid::regclass parent,f.conname,f.convalidated,
 pg_get_constraintdef(f.oid) definition FROM pg_constraint f WHERE f.contype='f'
 AND f.confrelid IN(SELECT oid FROM graph) ORDER BY f.conrelid::regclass::text,f.confrelid::regclass::text,f.conname;

-- Non-FK character references (arrays/JSON and mixed entity IDs need semantic review).
SELECT a.attrelid::regclass relation,a.attname,format_type(a.atttypid,a.atttypmod) type
FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind IN('r','p') AND a.attnum>0 AND NOT a.attisdropped
AND (a.attname ILIKE '%character%' OR a.attname IN('target_id','source_id','dropped_by','location_kind','location_id',
 'state','events','payload','result','snapshot','item_snapshot','member_buffs','recent_member_ids','event','final_summary'))
ORDER BY a.attrelid::regclass::text,a.attnum;

-- Reset table DELETE/deferred triggers and any newly attached character fences; metadata only.
WITH targets(oid) AS (
 SELECT to_regclass('public.'||quote_ident(v.name))::oid FROM (VALUES
('active_effects'),
('character_ability_loadout'),
('character_class_bonds'),
('character_creation_log'),
('character_creation_origin'),
('character_guide_reads'),
('character_inventory'),
('character_inventory_action_request'),
('character_lifecycle_receipt'),
('character_materials'),
('character_npc_gifts'),
('character_resource_settlement_state'),
('character_special_travel_request'),
('character_stance'),
('character_stance_request'),
('character_visited_nodes'),
('character_waymark'),
('characters'),
('combat2_canary_node'),
('combat2_departure_request'),
('combat2_diagnostic_server_event'),
('combat2_diagnostic_session'),
('combat2_dispatch_schedule_state'),
('combat2_party_departure_member'),
('combat2_party_departure_request'),
('combat2_player_presence'),
('combat2_respawn_config'),
('combat2_respawn_request'),
('combat2_test_arena'),
('combat2_test_arena_access'),
('combat2_test_arena_creature'),
('combat2_test_arena_node'),
('combat2_test_arena_request'),
('combat2_test_arena_stance_snapshot'),
('combat2_test_arena_stance_snapshot_header'),
('combat2_test_presence'),
('combat2_test_run'),
('combat2_test_run_batch'),
('combat2_test_run_event'),
('combat2_tick_notification'),
('combat_actions'),
('combat_audit_log'),
('combat_config'),
('combat_sessions'),
('combat_soak_access'),
('combat_soak_scopes'),
('effects_catchup_dispatch'),
('effects_catchup_log'),
('encounter_access_grants'),
('encounter_cast_events'),
('encounter_contributions'),
('encounter_creatures'),
('encounter_death_loot'),
('encounter_engagements'),
('encounter_kill_awards'),
('encounter_participants'),
('encounter_tick_batches'),
('encounters'),
('families'),
('family_members'),
('family_requests'),
('hidden_path_search_request'),
('issue_reports'),
('marketplace_listings'),
('node_arrival_group'),
('node_boss_ability_cooldown'),
('node_creature'),
('node_death_loot'),
('node_effect'),
('node_encounter'),
('node_fighter'),
('node_ground_loot'),
('node_intent'),
('node_participation'),
('node_pending_event'),
('node_reward_claim'),
('node_tick_batch'),
('node_tick_log'),
('parties'),
('party_combat_log'),
('party_members'),
('party_operation_request'),
('progression_character_state'),
('progression_class_growth_milestone'),
('progression_command_control'),
('progression_receipt'),
('progression_renown_key'),
('progression_respec_milestone'),
('summon_requests'),
('unique_item_instance'),
('world_slumber_log')
 ) v(name)
)
SELECT t.tgrelid::regclass relation,t.tgname,t.tgisinternal,t.tgenabled,t.tgdeferrable,t.tginitdeferred,
 pg_get_triggerdef(t.oid) trigger_definition,t.tgfoid::regprocedure function_identity,
 pg_get_userbyid(p.proowner) function_owner,p.prosecdef,p.proconfig,
 CASE WHEN p.proname IN ('unique_holder_before_delete','unique_holder_finalize_delete','combat2_refuse_invalid_stance_equipment_change')
 THEN md5(replace(p.prosrc,chr(13)||chr(10),chr(10))) END reviewed_delete_body_md5
FROM pg_trigger t JOIN pg_proc p ON p.oid=t.tgfoid WHERE t.tgrelid IN(SELECT oid FROM targets)
ORDER BY t.tgrelid::regclass::text,t.tgname;

-- No secret-bearing columns; role counts/IDs are sufficient for preservation checks.
SELECT current_user inspector,
 CASE WHEN NOT row_security_active('public.characters'::regclass) THEN (SELECT count(*) FROM public.characters) END characters,
 CASE WHEN NOT row_security_active('public.characters'::regclass) THEN (SELECT count(*) FROM public.characters WHERE deleted_at IS NOT NULL) END tombstones,
 NOT(row_security_active('public.characters'::regclass) OR row_security_active('public.character_materials'::regclass)) materials_visibility_complete,
 CASE WHEN NOT(row_security_active('public.characters'::regclass) OR row_security_active('public.character_materials'::regclass))
 THEN (SELECT count(*) FROM public.character_materials m WHERE NOT EXISTS(SELECT 1 FROM public.characters c WHERE c.id=m.character_id)) END orphan_material_rows;
