/**
 * Client-side mirror of the pure `resolveEffectTicks` logic from
 * `supabase/functions/_shared/combat-resolver.ts`.
 *
 * This file exists solely so Vitest can import and test the deterministic
 * resolver without touching the Deno edge-function import graph.
 * The edge functions remain the authoritative copy.
 *
 * IMPORTANT: keep this in sync with the _shared version. Both are pure
 * (no DB calls) and must produce identical results.
 */

import { resolveDamage } from '@/shared/combat/resolution';
import {
  amplify,
  buildAmpSnapshot,
  isPeriodicStatus,
  type ActiveEffectRow,
  type DamageAmpInstance,
  type DamageAmpStatusDef,
} from '@/shared/combat/creature-damage-modifiers';

// ── Types ────────────────────────────────────────────────────────

export interface LootQueueEntry {
  nodeId: string;
  lootTableId: string | null;
  itemId: string | null;
  creatureName: string;
  dropChance: number;
  mode: 'legacy' | 'item_pool';
  creatureLevel?: number;
  creatureRarity?: string | null;
}

export interface EffectTickResult {
  /** Effect IDs that should be deleted (expired or target killed) */
  expiredIds: string[];
  /** Creature IDs killed by effects this resolution */
  newKills: Set<string>;
  /** Loot queue entries generated by effect kills */
  lootQueue: LootQueueEntry[];
  /** Events/messages generated during processing */
  events: { type: string; message: string; ability_key?: string }[];
  /** Cleared DoT info for client sync */
  clearedDots: { character_id: string; creature_id: string; dot_type: string }[];
  /** Effects whose next_tick_at was advanced (for DB upsert) */
  advancedEffects: any[];
}

// ── resolveEffectTicks ───────────────────────────────────────────
/**
 * Process active effects against creature HP.
 *
 * **Single-tick mode** (`tickTime` provided): process effects due at that
 * specific tick timestamp. Used by `combat-tick` once per tick inside its loop.
 *
 * **Bulk mode** (`tickTime` omitted, `now` required): calculate all elapsed
 * ticks per effect and process them all. Used by `combat-catchup` on node entry.
 *
 * @param effects       In-memory active_effects rows for this node
 * @param cHp           Mutable creature HP map (updated in place)
 * @param cKilled       Mutable set of already-killed creature IDs
 * @param creatures     Full creature rows (for loot info on kill)
 * @param tickCap       Max ticks per effect in bulk mode
 * @param opts.tickTime If set, single-tick mode at this timestamp
 * @param opts.now      Current wall-clock ms (required for bulk mode)
 * @param opts.memberNameMap  Map of source_id → character name for messages
 */
export function resolveEffectTicks(
  effects: any[],
  cHp: Record<string, number>,
  cKilled: Set<string>,
  creatures: any[],
  tickCap: number,
  opts: {
    tickTime?: number;
    now?: number;
    memberNameMap?: Record<string, string>;
    /**
     * Target-side incoming-damage amplification (e.g. Chilled).
     * - `snapshot`: frozen per-creature instances for single-tick mode, so the
     *   result never depends on party iteration order.
     * - `effects` + `defs`: source rows for bulk mode, where amplification is
     *   recomputed for every simulated historical tick from each instance's
     *   active window.
     */
    amp?: {
      snapshot?: Record<string, DamageAmpInstance[]>;
      effects?: ActiveEffectRow[];
      defs?: Record<string, DamageAmpStatusDef>;
    };
    /** Applied-status definitions by `effect_type` (periodicity authority). */
    statusDefs?: Record<string, DamageAmpStatusDef>;
  } = {},
): EffectTickResult {
  const { tickTime, now, memberNameMap, amp, statusDefs } = opts;
  const isSingleTick = tickTime !== undefined;

  const expiredIds: string[] = [];
  const newKills = new Set<string>();
  const lootQueue: LootQueueEntry[] = [];
  const events: { type: string; message: string; ability_key?: string }[] = [];
  const clearedDots: { character_id: string; creature_id: string; dot_type: string }[] = [];
  const advancedEffects: any[] = [];

  /**
   * Periodicity has ONE authority: the status classification. When definitions
   * are unavailable (seeded/offline paths) a row that carries no tick cadence
   * cannot be periodic, which is the safe fallback.
   */
  const isPeriodic = (eff: any): boolean => {
    const def = statusDefs?.[eff.effect_type];
    if (def) return isPeriodicStatus(def);
    return eff.next_tick_at !== null && eff.next_tick_at !== undefined;
  };

  const statusLabel = (effectType: string): string => {
    const def = (statusDefs?.[effectType] ?? amp?.defs?.[effectType]) as
      (DamageAmpStatusDef & { label?: string }) | undefined;
    if (def?.label) return def.label;
    return effectType.charAt(0).toUpperCase() + effectType.slice(1);
  };

  /** Amplification instances active on `creatureId` at time `at`. */
  const ampFor = (creatureId: string, at: number): DamageAmpInstance[] | undefined => {
    if (amp?.snapshot) return amp.snapshot[creatureId];
    if (amp?.effects && amp?.defs) {
      return buildAmpSnapshot(amp.effects, amp.defs, at)[creatureId];
    }
    return undefined;
  };

  for (const eff of effects) {
    // Skip effects on already-dead targets
    if (cKilled.has(eff.target_id) || cHp[eff.target_id] === undefined || cHp[eff.target_id] <= 0) {
      if (!cKilled.has(eff.target_id) && cHp[eff.target_id] !== undefined) {
        // HP is 0 but not in killed set — skip
      }
      continue;
    }

    const creature = creatures.find((cr: any) => cr.id === eff.target_id);
    if (!creature) continue;

    const charName = memberNameMap?.[eff.source_id] || 'Unknown';

    // ── Non-periodic statuses ────────────────────────────────
    // They share the application/refresh/expiry lifecycle but never tick
    // damage and never touch tick cadence.
    if (!isPeriodic(eff)) {
      const at = isSingleTick ? tickTime! : now!;
      if (eff.expires_at <= at) {
        eff._expired = true;
        expiredIds.push(eff.id);
        clearedDots.push({ character_id: eff.source_id, creature_id: eff.target_id, dot_type: eff.effect_type });
        events.push({
          type: `${eff.effect_type}_expired`,
          message: `${statusLabel(eff.effect_type)} fades from ${creature.name}.`,
          ability_key: eff.source_ability_key ?? undefined,
        });
      }
      continue;
    }


    if (isSingleTick) {
      // ── Single-tick mode ─────────────────────────────────────
      // Check expiry
      if (eff.expires_at <= tickTime!) {
        eff._expired = true;
        expiredIds.push(eff.id);
        clearedDots.push({ character_id: eff.source_id, creature_id: eff.target_id, dot_type: eff.effect_type });
        continue;
      }

      // Apply tick if due
      if (eff.next_tick_at <= tickTime!) {
        const rawDmg = (eff.effect_type === 'bleed') ? eff.damage_per_tick : eff.stacks * eff.damage_per_tick;
        // Target-side incoming-damage modifiers (Chilled) — the ONE shared stage,
        // applied immediately before the final HP resolution.
        const totalDmg = amplify(rawDmg, 'dot', ampFor(eff.target_id, tickTime!));
        cHp[eff.target_id] = resolveDamage({ amount: totalDmg, hp: cHp[eff.target_id] }).hpAfter;

        const verb = eff.effect_type === 'bleed' ? 'bleeds from' : eff.effect_type === 'poison' ? 'suffers' : 'burns from';
        const sourceLabel = eff.effect_type === 'bleed'
          ? `${charName}'s Rend`
          : `${charName}'s ${eff.effect_type} (×${eff.stacks})`;
        const dmgLabel = totalDmg;

        events.push({
          type: 'dot_tick',
          message: `${creature.name} ${verb} ${sourceLabel}. [${dmgLabel}]`,
          // Canonical identity of the ability that applied the effect (when the
          // row carries one) — additive metadata, never a classifier input.
          ability_key: eff.source_ability_key ?? undefined,
        });

        eff.next_tick_at += eff.tick_rate_ms;
        advancedEffects.push(eff);

        if (cHp[eff.target_id] <= 0 && !cKilled.has(eff.target_id)) {
          cKilled.add(eff.target_id);
          newKills.add(eff.target_id);
          pushCreatureLoot(creature, eff.target_id, lootQueue);
        }
      }
    } else {
      // ── Bulk mode ────────────────────────────────────────────
      const currentNow = now!;
      const elapsedMs = currentNow - eff.next_tick_at;
      if (elapsedMs < 0) continue; // Not due yet

      const ticksToProcess = Math.floor(elapsedMs / eff.tick_rate_ms) + 1;
      const maxTicksByExpiry = Math.max(0, Math.floor((eff.expires_at - eff.next_tick_at) / eff.tick_rate_ms) + 1);
      const ticks = Math.min(ticksToProcess, tickCap, maxTicksByExpiry);

      if (ticks <= 0) {
        if (currentNow >= eff.expires_at) expiredIds.push(eff.id);
        continue;
      }

      for (let t = 0; t < ticks; t++) {
        const tt = eff.next_tick_at + t * eff.tick_rate_ms;
        if (tt > eff.expires_at) break;
        if (cKilled.has(eff.target_id) || cHp[eff.target_id] <= 0) break;

        const rawDmg = (eff.effect_type === 'bleed') ? eff.damage_per_tick : eff.stacks * eff.damage_per_tick;
        // Amplification is resolved per simulated historical tick from each
        // instance's active window — never one present-time snapshot.
        const totalDmg = amplify(rawDmg, 'dot', ampFor(eff.target_id, tt));
        cHp[eff.target_id] = resolveDamage({ amount: totalDmg, hp: cHp[eff.target_id] }).hpAfter;


        if (cHp[eff.target_id] <= 0 && !cKilled.has(eff.target_id)) {
          cKilled.add(eff.target_id);
          newKills.add(eff.target_id);
          pushCreatureLoot(creature, eff.target_id, lootQueue);
        }
      }

      const newNextTickAt = eff.next_tick_at + ticks * eff.tick_rate_ms;
      if (newNextTickAt >= eff.expires_at || cKilled.has(eff.target_id)) {
        expiredIds.push(eff.id);
      } else {
        eff.next_tick_at = newNextTickAt;
        advancedEffects.push(eff);
      }
    }
  }

  return { expiredIds, newKills, lootQueue, events, clearedDots, advancedEffects };
}

// ── Helper: push loot queue entries for a killed creature ─────────
function pushCreatureLoot(creature: any, _creatureId: string, lootQueue: LootQueueEntry[]) {
  const nodeId = creature.node_id;
  const lootMode = creature.loot_mode || 'legacy_table';

  // item_pool mode — delegate to processLootDrops for DB-based pool resolution
  if (lootMode === 'item_pool') {
    lootQueue.push({
      nodeId,
      lootTableId: null,
      itemId: null,
      creatureName: creature.name,
      // Per-creature drop_chance is an explicit override. When null, processLootDrops
      // falls back to the pool config's per-rarity default.
      dropChance: creature.drop_chance ?? -1,
      mode: 'item_pool',
      creatureLevel: creature.level,
      creatureRarity: creature.rarity ?? null,
    });
    return;
  }

  // salvage_only — no item loot
  if (lootMode === 'salvage_only') return;

  // legacy_table mode
  if (creature.loot_table_id) {
    lootQueue.push({
      nodeId,
      lootTableId: creature.loot_table_id,
      itemId: null,
      creatureName: creature.name,
      dropChance: creature.drop_chance ?? 0.5,
      mode: 'legacy',
    });
  } else {
    const lt = (creature.loot_table || []) as any[];
    for (const entry of lt) {
      if (entry.type === 'gold') continue;
      if (Math.random() <= (entry.chance || 0.1)) {
        lootQueue.push({
          nodeId,
          lootTableId: null,
          itemId: entry.item_id,
          creatureName: creature.name,
          dropChance: 1,
          mode: 'legacy',
        });
      }
    }
  }
}

