import { describe,expect,it,vi } from 'vitest';
import { createPartyApi,createPartyMutationCoordinator,decodePartyMutation,decodePartyState } from './party-api';

const A='11111111-1111-4111-8111-111111111111', P='22222222-2222-4222-8222-222222222222', T='33333333-3333-4333-8333-333333333333', M='44444444-4444-4444-8444-444444444444', R='55555555-5555-4555-8555-555555555555';
describe('authoritative party adapter',()=>{
 it('uses the exact discriminated mutation RPC and returns only allowlisted outcomes',async()=>{const rpc=vi.fn().mockResolvedValue({data:{ok:true,kind:'invited',membership_id:M,private:'ignored'},error:null});const result=await createPartyApi(rpc).mutate({actorCharacterId:A,operation:'invite',partyId:P,targetCharacterId:T,membershipId:null,requestId:R});expect(rpc).toHaveBeenCalledWith('party_mutate',{_actor_character_id:A,_operation:'invite',_party_id:P,_target_character_id:T,_membership_id:null,_request_id:R});expect(result.value).toEqual({ok:true,kind:'invited',membershipId:M});expect(decodePartyMutation({ok:true,kind:'invented'})).toBeNull();});
 it('strictly projects safe party state without account data',()=>{const decoded=decodePartyState({ok:true,kind:'party_state',party:{id:P,leaderId:A,tankId:A,createdAt:'2026-09-08T00:00:00Z',userId:'hidden'},members:[{id:M,characterId:A,status:'accepted',isFollowing:false,character:{id:A,name:'A',gender:'male',race:'Human',class:'Fighter',level:1,hp:10,maxHp:10,currentNodeId:null,dex:5,email:'hidden'}}],incomingInvitations:[],outgoingInvitations:[]});expect(decoded?.party?.leader_id).toBe(A);expect(decoded).not.toHaveProperty('userId');expect(decoded?.members[0].character).not.toHaveProperty('email');});
 it('reuses a UUID after uncertainty, uses a new UUID after a definite result, and suppresses identical in-flight work',async()=>{let resolveFirst:(value:any)=>void=()=>{};const call=vi.fn().mockImplementationOnce(()=>new Promise(resolve=>{resolveFirst=resolve;})).mockResolvedValue({value:{ok:true,kind:'party_created'}});const ids=[R,'66666666-6666-4666-8666-666666666666'];const coordinator=createPartyMutationCoordinator(call,()=>ids.shift()!);coordinator.setActor(A);const input={operation:'create' as const,partyId:null,targetCharacterId:null,membershipId:null};const first=coordinator.submit('create',input);expect(coordinator.submit('create',input)).toBe(first);resolveFirst({error:'uncertain',uncertain:true});await first;await coordinator.submit('create',input);expect(call.mock.calls[0][0].requestId).toBe(R);expect(call.mock.calls[1][0].requestId).toBe(R);await coordinator.submit('create',input);expect(call.mock.calls[2][0].requestId).not.toBe(R);});
 it('marks late responses stale after an actor switch',async()=>{let resolve:(value:any)=>void=()=>{};const coordinator=createPartyMutationCoordinator(()=>new Promise(done=>{resolve=done}),()=>R);coordinator.setActor(A);const pending=coordinator.submit('create',{operation:'create',partyId:null,targetCharacterId:null,membershipId:null});coordinator.setActor(T);resolve({value:{ok:true,kind:'party_created'}});await expect(pending).resolves.toMatchObject({stale:true});});
 it('redacts transport errors and fails malformed state closed',async()=>{const api=createPartyApi(vi.fn().mockResolvedValue({data:null,error:{message:'private SQL'}}));expect(await api.state(A)).toEqual({error:'Party refresh failed.',uncertain:true});expect(decodePartyState({ok:true,kind:'party_state'})).toBeNull();});
 it.each([['follow','following'],['stop_following','not_following']] as const)('routes %s through the durable party mutation contract',async(operation,kind)=>{const rpc=vi.fn().mockResolvedValue({data:{ok:true,kind,party_id:P},error:null});const result=await createPartyApi(rpc).mutate({actorCharacterId:A,operation,partyId:P,targetCharacterId:null,membershipId:null,requestId:R});expect(result.value?.kind).toBe(kind);expect(rpc).toHaveBeenCalledExactlyOnceWith('party_mutate',expect.objectContaining({_operation:operation,_request_id:R}));});
});
