// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/list-characters.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-characters.ts
var list_characters_default = defineTool({
  name: "list_characters",
  title: "List characters",
  description: "List the signed-in player's characters in Wayfarers of Varneth with class, race, level, gold and vital resources.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("characters").select(
      "id, name, family_name, race, class, level, gold, hp, max_hp, cp, max_cp, mp, max_mp, ac, renown, last_online"
    ).order("name", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const characters = data ?? [];
    if (characters.length === 0) {
      return { content: [{ type: "text", text: "No characters yet \u2014 create one in the app first." }] };
    }
    const lines = characters.map(
      (c) => `${c.name}${c.family_name ? ` ${c.family_name}` : ""} \u2014 level ${c.level} ${c.race} ${c.class} \xB7 HP ${c.hp}/${c.max_hp} \xB7 CP ${c.cp}/${c.max_cp} \xB7 MP ${c.mp}/${c.max_mp} \xB7 AC ${c.ac} \xB7 ${c.gold} gold`
    );
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: { characters }
    };
  }
});

// src/lib/mcp/tools/get-character.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";
var get_character_default = defineTool2({
  name: "get_character",
  title: "Get character sheet",
  description: "Read the full sheet for one of the signed-in player's characters by name: attributes, resources, renown, progress and current location.",
  inputSchema: {
    name: z.string().trim().min(1).describe("Character's first name, e.g. 'Calikon'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: character, error } = await supabase.from("characters").select("*").ilike("name", name).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!character) {
      return {
        content: [{ type: "text", text: `No character named "${name}" on this account.` }],
        isError: true
      };
    }
    let location = null;
    if (character.current_node_id) {
      const { data: node } = await supabase.from("nodes").select("name, description").eq("id", character.current_node_id).maybeSingle();
      location = node ?? null;
    }
    const summary = [
      `${character.name}${character.family_name ? ` ${character.family_name}` : ""} \u2014 level ${character.level} ${character.race} ${character.class}`,
      `HP ${character.hp}/${character.max_hp} \xB7 CP ${character.cp}/${character.max_cp} \xB7 MP ${character.mp}/${character.max_mp} \xB7 AC ${character.ac}`,
      `STR ${character.str} \xB7 DEX ${character.dex} \xB7 CON ${character.con} \xB7 INT ${character.int} \xB7 WIS ${character.wis} \xB7 CHA ${character.cha}`,
      `XP ${character.xp} \xB7 Renown ${character.renown ?? 0} \xB7 Boss Hunter Points ${character.bhp} \xB7 ${character.gold} gold`,
      location ? `Location: ${location.name}` : "Location: unknown"
    ].join("\n");
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: { character, location }
    };
  }
});

// src/lib/mcp/tools/list-inventory.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var list_inventory_default = defineTool3({
  name: "list_inventory",
  title: "List inventory",
  description: "List the equipment and inventory of one of the signed-in player's characters, including rarity, slot, durability and equipped state.",
  inputSchema: {
    character_name: z2.string().trim().min(1).describe("Character's first name."),
    equipped_only: z2.boolean().optional().describe("When true, only return equipped items.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ character_name, equipped_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: character, error: charError } = await supabase.from("characters").select("id, name").ilike("name", character_name).maybeSingle();
    if (charError) {
      return { content: [{ type: "text", text: charError.message }], isError: true };
    }
    if (!character) {
      return {
        content: [{ type: "text", text: `No character named "${character_name}" on this account.` }],
        isError: true
      };
    }
    let query = supabase.from("character_inventory").select(
      "id, equipped_slot, current_durability, applied_gems, crafted_level, items(name, rarity, slot, item_type, level, weapon_die, stats, description)"
    ).eq("character_id", character.id);
    if (equipped_only) query = query.not("equipped_slot", "is", null);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    if (rows.length === 0) {
      return { content: [{ type: "text", text: `${character.name} carries nothing.` }] };
    }
    const lines = rows.map((row) => {
      const item = row.items ?? {};
      const equipped = row.equipped_slot ? ` [equipped: ${row.equipped_slot}]` : "";
      return `${item.name ?? "Unknown item"} (${item.rarity ?? "?"}${item.slot ? `, ${item.slot}` : ""}) \u2014 durability ${row.current_durability}${equipped}`;
    });
    return {
      content: [{ type: "text", text: `${character.name}'s belongings:
${lines.join("\n")}` }],
      structuredContent: { character: character.name, items: rows }
    };
  }
});

// src/lib/mcp/tools/describe-location.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var describe_location_default = defineTool4({
  name: "describe_location",
  title: "Describe a world location",
  description: "Describe a location (node) in the world of Varneth: its description, region, area, services and exits. Omit the name to describe where a character currently stands.",
  inputSchema: {
    node_name: z3.string().trim().min(1).optional().describe("Location name, e.g. 'Hearthvale Square'."),
    character_name: z3.string().trim().min(1).optional().describe("Describe where this character of the signed-in player currently stands.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ node_name, character_name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!node_name && !character_name) {
      return {
        content: [{ type: "text", text: "Provide either node_name or character_name." }],
        isError: true
      };
    }
    const supabase = supabaseForUser(ctx);
    let nodeId = null;
    if (!node_name && character_name) {
      const { data: character } = await supabase.from("characters").select("current_node_id").ilike("name", character_name).maybeSingle();
      if (!character?.current_node_id) {
        return {
          content: [{ type: "text", text: `Could not locate a character named "${character_name}".` }],
          isError: true
        };
      }
      nodeId = character.current_node_id;
    }
    const selection = "id, name, description, x, y, connections, is_inn, is_vendor, is_blacksmith, is_jewelcrafter, is_marketplace, is_trainer, is_teleport, is_soulforge, is_stonebinder, is_heraldry, class_hall, regions(name), areas(name, area_type)";
    const query = supabase.from("nodes").select(selection);
    const { data: node, error } = nodeId ? await query.eq("id", nodeId).maybeSingle() : await query.ilike("name", node_name).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!node) {
      return {
        content: [{ type: "text", text: `No known location matching "${node_name}".` }],
        isError: true
      };
    }
    const services = Object.entries(node).filter(([key, value]) => key.startsWith("is_") && value === true).map(([key]) => key.replace("is_", "").replace(/_/g, " "));
    const exits = Array.isArray(node.connections) ? node.connections.map((c) => c?.direction ?? c).filter(Boolean) : [];
    const text = [
      `${node.name} (${node.regions?.name ?? "unknown region"}${node.areas?.name ? ` \xB7 ${node.areas.name}` : ""}) at grid ${node.x},${node.y}`,
      node.description,
      services.length ? `Services: ${services.join(", ")}` : "Services: none",
      exits.length ? `Exits: ${exits.join(", ")}` : "Exits: none recorded"
    ].join("\n\n");
    return { content: [{ type: "text", text }], structuredContent: { node } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gpclaklkaolyzfnooajt";
var mcp_default = defineMcp({
  name: "wovarneth",
  title: "WoVarneth",
  version: "0.1.0",
  instructions: "Tools for Wayfarers of Varneth, a fantasy MUD. Use `list_characters` to see the signed-in player's characters, `get_character` for a full character sheet, `list_inventory` for their gear, and `describe_location` for world locations. All tools act as the signed-in player and only expose their own characters.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_characters_default, get_character_default, list_inventory_default, describe_location_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
